volumes:
  linkding:
    external: true

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - linkding:/etc/linkding/data
    restart: unless-stopped
    environment:
      - LD_SUPERUSER_PASSWORD=${LINKDING_PASS}
      - LD_SUPERUSER_NAME=admin
      # - LD_DISABLE_BACKGROUND_TASKS=False # Option to disable background tasks
      # - LD_DISABLE_URL_VALIDATION=False # Option to disable URL validation for bookmarks completely
      # - LD_ENABLE_AUTH_PROXY=False # Enables support for authentication proxies such as Authelia
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkding.rule=Host(`link.${DOMAIN}`)
      - traefik.http.services.linkding.loadbalancer.server.port=9090
      - traefik.docker.network=internal
      - homepage.group=Apps
      - homepage.name=Linkding
      - homepage.icon=linkding.png
      - homepage.href=https://link.${DOMAIN}
      - homepage.description=Bookmark Manager
      - docker-volume-backup.stop-during-backup=true
    networks:
      - internal
