services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie
    hostname: mealie
    depends_on:
      - mealie-api
    environment:
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    # ports:
    #   - "9925:3000"
    expose:
      - 3000
    volumes:
      - ${DOCKERM}/mealie:/app/data/
    networks:
      - internal
    labels:
     - traefik.enable=true
     - traefik.http.routers.mealie.rule=Host(`mealie.${DOMAIN}`)
     - traefik.http.services.mealie.loadbalancer.server.port=3000
     - traefik.docker.network=internal

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    hostname: mealie-api
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ${DOCKERM}/mealie:/app/data/
    networks:
     - internal
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAIN}
    restart: unless-stopped
