services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ${DOCKERM}/redbot:/data
    environment:
      # - TOKEN=${REDBOT_TOKEN}
      # - PREFIX=.
      - TZ=${TZ}
      - PUID=1000

networks:
  internal:
    external: true
