services:
  migrate:
    image: alpine
    volumes:
      - ts-socket:/from
      - /opt/docker/ts-socket:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  ts-socket:
    external: true
