services:
  migrate:
    image: alpine
    volumes:
      - nextcloud:/from
      - /opt/docker/nextcloud:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  nextcloud:
    external: true
