## Add your compose file here
services:
  hello_world:
    image: hello-world
    # networks:
    #   - default
    # ports:
    #   - 3000:3000
    volumes:
      - ${DOCKERM}/test/test:/data

# networks:
#   default: {}

# volumes:
#   data:
