services:
  migrate:
    image: alpine
    volumes:
      - umami-db:/from
      - /opt/docker/umami-db:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  umami-db:
    external: true
