services:
  migrate:
    image: alpine
    volumes:
      - netdatalib:/from
      - /opt/docker/netdata/lib:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  netdatalib:
    external: true
