services:
  migrate:
    image: alpine
    volumes:
      - linkding:/from
      - /opt/docker/linkding:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  linkding:
    external: true
