services:
  migrate:
    image: alpine
    volumes:
      - crowdsec-config:/from
      - /opt/docker/crowdsec/config:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  crowdsec-config:
    external: true
