services:
  migrate:
    image: alpine
    volumes:
      - minio:/from
      - /opt/docker/minio:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  minio:
    external: true
