services:
  migrate:
    image: alpine
    volumes:
      - speed-db:/from
      - /opt/docker/speed-db:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  speed-db:
    external: true
