services:
  migrate:
    image: alpine
    volumes:
      - redbot:/from
      - /opt/docker/redbot:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  redbot:
    external: true
