services:
  migrate:
    image: alpine
    volumes:
      - qbit:/from
      - /opt/docker/qbit:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  qbit:
    external: true
