services:
  migrate:
    image: alpine
    volumes:
      - mealie:/from
      - /opt/docker/mealie:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  mealie:
    external: true
