services:
  migrate:
    image: alpine
    volumes:
      - authentik:/from
      - /opt/docker/authentik:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  authentik:
    external: true
