services:
  migrate:
    image: alpine
    volumes:
      - immich-db:/from
      - /opt/docker/immich-db:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  immich-db:
    external: true
