services:
  migrate:
    image: alpine
    volumes:
      - beszel-socket:/from
      - /opt/docker/beszel-socket:/to
    command: sh -c "cd /from && cp -av . /to/"
    restart: "no"
volumes:
  beszel-socket:
    external: true
