# docker network create --driver bridge --attachable --subnet 172.20.0.0/24 internal
# docker network create --driver bridge --attachable --subnet 10.99.0.0/24 public
# docker network create --driver bridge --attachable --subnet 172.20.1.0/24 traefik
# docker network create --driver bridge --attachable --internal --subnet 172.20.2.0/24 kop
# docker network create --driver bridge --attachable --internal --subnet 172.20.3.0/24 crowdsec

services:
  mongo:
    image: mongo
    container_name: komo-mongo
    labels:
      - komodo.skip
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
      - stack
    logging:
      driver: local
    # ports:
    #   - 27017:27017
    volumes:
      - ${DOCKERM}/komodo:/data/db

  core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo
    networks:
      - internal
      - public
      - stack
    labels:
      - komodo.skip
      - traefik.enable=true
      - traefik.http.routers.komodo.rule=Host(`komo.${CASA}`)
      - traefik.http.routers.komodo.service=komodo
      - traefik.http.services.komodo.loadbalancer.server.port=9120
      - traefik.docker.network=internal
      # - kop.namespace=public
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: local
    ports:
      - 9120:9120
    volumes:
      - ${DOCKERM}/core.config.toml:/config/config.toml
      - ${DOCKERM}/dumps/komodo:/backups
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  internal:
    external: true
  public:
    external: true
  stack:
    internal: true
