services:
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo
    networks:
      - internal
      - public
      - komodo
    labels:
      - komodo.skip
      - traefik.enable=true
      - traefik.http.routers.komodo.rule=Host(`komo.${CASA}`)
      - traefik.http.routers.komodo.service=komodo
      - traefik.http.services.komodo.loadbalancer.server.port=9120
      - traefik.docker.network=internal
      # - kop.namespace=public
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - 9120:9120
    volumes:
      - ${DOCKERM}/core.config.toml:/config/config.toml
      - ${DOCKERM}/dumps/komodo:/backups
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  internal:
    external: true
  public:
    external: true
  komodo:
    external: true
