[[server]]
name = "pbox"
[server.config]
address = "https://host.docker.internal:8120"
enabled = true

##

[[stack]]
name = "arr"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media/arr"
file_paths = ["arr.yaml", "../../pbox.yaml"]
additional_env_files = ["../../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
SONARR_API_KEY="op://Secrets/Sonarr/credential"
RADARR_API_KEY="op://Secrets/Radarr/credential"
LIDARR_API_KEY="op://Secrets/Lidarr/credential"
PROWLARR_API_KEY="op://Secrets/Prowlarr/credential"
OVERSEERR_API_KEY="op://Secrets/Overseerr/credential"
READARR_API_KEY="op://Secrets/Readarr/credential"
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD="op://Secrets/qBit/password"
TAUTULLI_API_KEY="op://Secrets/Tautulli/credential"

"""

##

[[stack]]
name = "auth"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
webhook_enabled = false
run_directory = "network"
file_paths = ["authentik.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
PG_PASS="op://Secrets/Authentik/db_pass"
AUTHENTIK_SECRET_KEY="op://Secrets/Authentik/secret_key"
OUTPOST_TOKEN="op://Secrets/Authentik/outpost_token"
SMTPHOST="op://Secrets/SMTP/host"
SMTPUSER="op://Secrets/SMTP/API Key"
SMTPASS="op://Secrets/SMTP/Secret Key"

"""

##

[[stack]]
name = "code"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "misc"
file_paths = [
  "codeserver.yaml",
  "../pbox.yaml"
]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "dashboard"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "dash"
file_paths = ["homepage.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN="op://Secrets/OpenWeatherMap/credential"
CROWDSEC_PASS="op://Secrets/Crowdsec/main_instance_pass"
"""

##

[[stack]]
name = "discord"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "misc/discord"
file_paths = [
  "redbot.yaml",
  "muse.yaml",
  "doplarr.yaml",
  "membarr.yaml",
  "../../pbox.yaml"
]
additional_env_files = ["../../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
GOOGLE_API="op://Secrets/Goggleapis/credential"
REDBOT_TOKEN="op://Secrets/Redbot/token"
MUSE_TOKEN="op://Secrets/Muse/credential"
MEMBARR_TOKEN="op://Secrets/Membarr/credential"
DOPLARR_TOKEN="op://Secrets/Doplarr/credential"
OVERSEERR_API_KEY="op://Secrets/Overseerr/credential"

"""

##

[[stack]]
name = "dns"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["dns.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "downs"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media/downs"
file_paths = [
  "qbit-vpn.yaml",
  "sab.yaml",
  "../../pbox.yaml"
]
additional_env_files = ["../../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
PIA_USER="op://Secrets/pia/username"
PIA_PASS="op://Secrets/pia/password"
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD="op://Secrets/qBit/password"
SABNZBD_API_KEY="op://Secrets/Sabnzbd/credential"
WIREGUARD_PRIVATE_KEY="op://Secrets/Wireguard/credential"
GLUETUN_APIKEY="op://Secrets/Gluetun/credential"
"""

##

[[stack]]
name = "external"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["external.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
CF_DNS_API_TOKEN="op://Secrets/Cloudflare/credential"
CF_TRAEFIK_TUNNEL_TOKEN=op://Secrets/Cloudflare/boneyards
CS_TRAEFIK_BOUNCER_KEY="op://Secrets/Crowdsec/credential"
BOUNCER_HOST=crowdsec:8080
"""

##

[[stack]]
name = "internal"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["internal.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
CF_DNS_API_TOKEN="op://Secrets/Cloudflare/credential"
"""

##

[[stack]]
name = "kop"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["kop.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "linkding"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "misc"
file_paths = ["linkding.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
LINKDING_PASS="op://Secrets/Linkding/password"

"""

##

[[stack]]
name = "media"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = [
  "plex.yaml",
  "jellyfin.yaml",
  "stash.yaml",
  "../pbox.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
PLEX_TOKEN="op://Secrets/Plex/credential"
JELLYFIN_API_KEY="op://Secrets/Jellyfin/credential"
"""

##

[[stack]]
name = "monitor"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["monitor.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
INFLUXDB_PASS="op://Secrets/InfluxDB/password"
INFLUXDB_TOKEN="op://Secrets/InfluxDB/token"
"""

##

[[stack]]
name = "system"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "system"
file_paths = [
  "tailsocket.yaml",
  "dozzle.yaml",
  "scrutiny.yaml",
  "cache.yaml",
  "../pbox.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
DISCORDURL="op://Secrets/Discord Webhooks/logs/pbox"
TS_AUTHKEY="op://Secrets/v4xfq7ijumolhvtybuk4hepdfy/socket"
"""

##

[[stack]]
name = "web"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["umami.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
APP_SECRET="op://Secrets/Umami/credential"
UMAMI_DB_PASSWORD="op://Secrets/Umami/db"
"""

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params = {}

##

[[resource_sync]]
name = "pbox"
[resource_sync.config]
repo = "cwelsys/stacks"
git_account = "cwelsys"
resource_path = ["komodo.toml"]
managed = true