[[server]]
name = "pbox"
[server.config]
address = "https://host.docker.internal:8120"
enabled = true

##

[[stack]]
name = "arr"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "arr"
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
SONARR_API_KEY="op://Secrets/Sonarr/credential"
RADARR_API_KEY="op://Secrets/Radarr/credential"
LIDARR_API_KEY="op://Secrets/Lidarr/credential"
PROWLARR_API_KEY="op://Secrets/Prowlarr/credential"
OVERSEERR_API_KEY="op://Secrets/Overseerr/credential"
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD="op://Secrets/qBit/password"
DOPLARR_TOKEN="op://Secrets/Doplarr/credential"
MEMBARR_TOKEN="op://Secrets/Membarr/credential"
TAUTULLI_API_KEY="op://Secrets/Tautulli/credential"
"""

##

[[stack]]
name = "auth"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "auth"
file_paths = ["authentik.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
AUTHENTIK_TAG=2025.2
PG_PASS="op://Secrets/Authentik/db_pass"
AUTHENTIK_SECRET_KEY="op://Secrets/Authentik/secret_key"
AUTHENTIK_TRAEFIK_OUTPUT_TOKEN=
AUTHENTIK_TRAEFIK_EXT_OUTPOST_TOKEN=
SMTPHOST=in-v3.mailjet.com
AUTHENTIK_EMAIL__PORT=25
SMTPUSER="op://Secrets/SMTP/API Key"
SMTPASS="op://Secrets/SMTP/Secret Key"

"""

##

[[stack]]
name = "crowdsec"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["../pbox.yaml", "crowdsec.yaml"]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "dashboard"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "dash"
file_paths = ["../pbox.yaml", "homepage.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN="op://Secrets/OpenWeatherMap/credential"
"""

##

[[stack]]
name = "data"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "data"
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
POSTGRES_PASSWORD="op://Secrets/2doyirimsnblvjuilo73gwfvgq/password"



"""

##

[[stack]]
name = "dns"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["../pbox.yaml", "dns.yaml"]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "downs"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "downs"
file_paths = [
  "../pbox.yaml",
  "qbit-vpn.yaml",
  "sab.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
PIA_USER="op://Secrets/pia/username"
PIA_PASS="op://Secrets/pia/password"
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD="op://Secrets/qBit/password"
SABNZBD_API_KEY="op://Secrets/Sabnzbd/credential"
WIREGUARD_PRIVATE_KEY="op://Secrets/Wireguard/credential"
GLUETUN_APIKEY="op://Secrets/Gluetun/credential"
"""

##

[[stack]]
name = "external"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = [
  "../pbox.yaml",
  "traefik-external.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
CF_DNS_API_TOKEN="op://Secrets/Cloudflare/credential"
CF_TRAEFIK_TUNNEL_TOKEN=op://Secrets/Cloudflare/boneyards
CS_TRAEFIK_BOUNCER_KEY="op://Secrets/Crowdsec/credential"
BOUNCER_HOST=crowdsec:8080
"""

##

[[stack]]
name = "internal"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = [
  "../pbox.yaml",
  "traefik-internal.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
CF_DNS_API_TOKEN="op://Secrets/Cloudflare/credential"
"""

##

[[stack]]
name = "kop"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["../pbox.yaml", "kop.yaml"]
additional_env_files = ["../global.env"]

##

[[stack]]
name = "media"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = [
  "plex.yaml",
  "jellyfin.yaml",
  "../pbox.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
PLEX_TOKEN="op://Secrets/Plex/credential"
JELLYFIN_API_KEY="op://Secrets/Jellyfin/credential"
"""

##

[[stack]]
name = "system"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "system"
file_paths = [
  "../pbox.yaml",
  "socket.yaml",
  "scrutiny.yaml",
  "cache.yaml"
]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
# RAPIPASS="op://Secrets/Socket Remote Api/password"
CERT_HOSTNAME="op://Secrets/Socket Remote Api/username"
DISCORDURL="op://Secrets/CM Discord Webhook/credential"
"""

##

[[stack]]
name = "web"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "web"
file_paths = ["umami.yaml", "../pbox.yaml"]
additional_env_files = ["../global.env"]
pre_deploy.command = """
OP_SERVICE_ACCOUNT_TOKEN=[[OP_SERVICE_ACCOUNT_TOKEN]] op inject -i .env -o .env --force
"""
environment = """
APP_SECRET="op://Secrets/Umami/credential"
UMAMI_DB_PASSWORD="op://Secrets/Umami/db"
"""

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params = {}

##

[[resource_sync]]
name = "pbox"
[resource_sync.config]
repo = "cwelsys/stacks"
git_account = "cwelsys"
resource_path = ["komodo.toml"]
managed = true