[[server]]
name = "pbox"
[server.config]
address = "https://host.docker.internal:8120"
enabled = true
cpu_warning = 92.0
disk_warning = 80.0

##

[[stack]]
name = "arr"
tags = ["media", "arr", "public"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["arr.yaml"]
environment = """
SONARR_API_KEY=[[SONARR__API]]
RADARR_API_KEY=[[RADARR__API]]
"""

##

[[stack]]
name = "audio"
tags = ["media"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["audio.yaml"]

##

[[stack]]
name = "backrest"
tags = ["infra", "backup"]
deploy = true
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "infra"
file_paths = ["backrest.yaml"]

##

[[stack]]
name = "beszel"
tags = ["monitor"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["beszel.yaml"]
environment = """
BESZEL_KEY=[[BESZEL__KEY]]
"""

##

[[stack]]
name = "bit-site"
tags = ["apps", "temp", "public"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["bit-site.yaml"]

##

[[stack]]
name = "book"
tags = ["media"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["book.yaml"]

##

[[stack]]
name = "core"
tags = ["infra", "public"]
deploy = true
[stack.config]
server = "pbox"
project_name = "stacks"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "infra"
file_paths = ["core.yaml"]

##

[[stack]]
name = "dozzle"
tags = ["monitor"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["dozzle.yaml"]

##

[[stack]]
name = "external"
tags = ["infra", "proxy", "public"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "infra"
file_paths = ["external.yaml"]
environment = """
CF_DNS_API_TOKEN=[[CLOUDFLARE__API]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
CF_TRAEFIK_TUNNEL_TOKEN=[[CLOUDFLARE__TUNNEL]]
CS_TRAEFIK_BOUNCER_KEY=[[CROWDSEC__BOUNCER]]
BOUNCER_HOST=crowdsec:8080
"""

##

[[stack]]
name = "ftp"
tags = ["apps", "files"]
deploy = true
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["ftp.yaml"]
environment = """
SFTPGO_DB_PASS=[[SFTPGO__PASSWORD]]
"""

##

[[stack]]
name = "game"
tags = ["media"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["game.yaml"]
environment = """
ROMM_DB_PW=[[ROMM__ROMMDB]]
MARIADB_PW=[[ROMM__MARIADB]]
ROMM_AUTH=[[ROMM__AUTH]]
SCREENSCRAPER_PW=[[ROMM__SCREENSC]]
RETROC_API_KEY=[[ROMM__RETRO_CHIEV]]
STEAMGRID_API_KEY=[[STEAMGRID__API]]
IGDB_CLIENT_ID=[[ROMM__IGDB_ID]]
IGDB_CLIENT_SECRET=[[ROMM__IGDB_SECRET]]
"""

##

[[stack]]
name = "homepage"
tags = ["monitor"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["homepage.yaml"]
environment = """
ABS_API_KEY=[[AUDIOBOOKSHELF__API]]
AUTHENTIK_API=[[AUTHENTIK__API]]
AUTOBRR_API_KEY=[[AUTOBRR__API]]
BAZARR_API_KEY=[[BAZARR__API]]
BESZEL_PW=[[BESZEL__PASSWORD]]
CALIBRE_PASS=[[CALIBRE__PASSWORD]]
CLOUDFLARE_ACC_ID=[[CLOUDFLARE__ACCOUNT]]
CLOUDFLARE_API=[[CLOUDFLARE__API]]
CROWDSEC_PASS=[[CROWDSEC__API]]
FINNHUB_TOKEN=[[FINNHUB__API]]
FRESHRSS_API_KEY=[[FRESHRSS__API]]
GITEA_API_KEY=[[GIT__PAT]]
GLUETUN_API_KEY=[[GLUETUN__API]]
GRAFANA_PASS=[[GRAFANA__API]]
HOMEASS_API_KEY=[[HOMEASSISTANT__API]]
HP_LOC_LABEL=[[HOMEPAGE__LOCATION]]
HP_LOC_LAT=[[HOMEPAGE__LAT]]
HP_LOC_LONG=[[HOMEPAGE__LONG]]
IMMICH_API_KEY=[[IMMICH__API]]
JELLYFIN_API_KEY=[[JELLYFIN__API]]
JELLYSEERR_API_KEY=[[JELLYSEERR__API]]
KAVITA_API_KEY=[[KAVITA__API]]
KOMO_API_KEY=[[KOMODO__API]]
KOMO_API_SECRET=[[KOMODO__API_SECRET]]
LIDARR_API_KEY=[[LIDARR__API]]
MEALIE_API_KEY=[[MEALIE__API]]
NEXTCLOUD_API_KEY=[[NEXTCLOUD__TOKEN]]
NEXTCLOUD_PW=[[NEXTCLOUD__PASSWORD]]
NEXTDNS_API_KEY=[[NEXTDNS__API]]
OPENWEATHERMAP_TOKEN=[[OPENWEATHERMAP__API]]
PLEX_API_KEY=[[PLEX__API]]
PROTON_ICAL=[[PROTON__ICAL]]
PROWLARR_API_KEY=[[PROWLARR__API]]
QBIT_PASSWORD=[[QBITTORRENT__PASSWORD]]
RADARR_API_KEY=[[RADARR__API]]
READARR_API_KEY=[[READARR__API]]
SABNZBD_API_KEY=[[SABNZBD__API]]
SLSKD_API_KEY=[[SLSK__API]]
SONARR_API_KEY=[[SONARR__API]]
STASH_API_KEY=[[STASH__API]]
TAUTULLI_API_KEY=[[TAUTULLI__API]]
TECHNITIUM_API_KEY=[[TECHNITIUM__API]]
TS_API=[[TAILSCALE__API]]
TUNNEL_ID=[[CLOUDFLARE__TUNNEL_ID]]
UPTIMEROBOT_API_KEY=[[UPTIMEROBOT__API]]
WHISPARR_API_KEY=[[WHISPARR__API]]
"""

##

[[stack]]
name = "immich"
tags = ["apps", "photos"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["immich.yaml"]
environment = """
IMMICH_PG_PASS=[[IMMICH__POSTGRES]]
"""

##

[[stack]]
name = "internal"
tags = ["infra", "proxy"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "infra"
file_paths = ["internal.yaml"]
environment = """
CF_DNS_API_TOKEN=[[CLOUDFLARE__API]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
"""

##

[[stack]]
name = "it-tools"
tags = ["apps"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["it-tools.yaml"]

##

[[stack]]
name = "jellyfin"
tags = ["media", "public"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["jellyfin.yaml"]
environment = """
JELLYPG_PASS=[[JELLYSTAT__POSTGRES]]
JELLYS_JWT=[[JELLYSTAT__JWT]]
"""

##

[[stack]]
name = "kiwi"
tags = ["media"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["kiwi.yaml"]

##

[[stack]]
name = "linkding"
tags = ["apps"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["linkding.yaml"]

##

[[stack]]
name = "membarr"
tags = ["bots", "discord"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "bots"
file_paths = ["membarr.yaml"]
environment = """
MEMBARR_TOKEN=[[DISCORD__MEMBARR]]
"""

##

[[stack]]
name = "monkey"
tags = ["apps"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["monkey.yaml"]

##

[[stack]]
name = "muse"
tags = ["bots", "discord"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "bots"
file_paths = ["muse.yaml"]
environment = """
GOOGLE_API=[[GOOGLE__API]]
MUSE_TOKEN=[[DISCORD__MUSE]]
"""

##

[[stack]]
name = "nextcloud"
tags = ["apps", "files", "public"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["nextcloud.yaml"]

##

[[stack]]
name = "redbot"
tags = ["bots", "discord"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "bots"
file_paths = ["redbot.yaml"]
environment = """
REDBOT_TOKEN=[[DISCORD__REDBOT]]
"""

##

[[stack]]
name = "requestarr"
tags = ["bots", "discord"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "bots"
file_paths = ["requestarr.yaml"]

##

[[stack]]
name = "sab"
tags = ["media", "download"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["sab.yaml"]

##

[[stack]]
name = "scrutiny"
tags = ["monitor"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["scrutiny.yaml"]

##

[[stack]]
name = "searxng"
tags = ["apps"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["searxng.yaml"]

##

[[stack]]
name = "slop"
tags = ["apps", "ai"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["slop.yaml"]
environment = """
OWUI_JWT=[[OPENWEBUI__JWT]]
"""

##

[[stack]]
name = "sock"
tags = ["infra"]
deploy = true
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "infra"
file_paths = ["sock.yaml"]

##

[[stack]]
name = "speed"
tags = ["monitor"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = ["speed.yaml"]
environment = """
SPEED_API=[[SPEEDTEST__API]]
"""

##

[[stack]]
name = "stash"
tags = ["media"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["stash.yaml"]

##

[[stack]]
name = "tortun"
tags = ["media", "download", "vpn"]
deploy = true
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media"
file_paths = ["tortun.yaml"]
environment = """
QBIT_USERNAME=admin
QBIT_PASSWORD=[[QBITTORRENT__PASSWORD]]
WIREGUARD_PRIVATE_KEY=[[PROTON__WIREGUARD]]
GLUETUN_APIKEY=[[GLUETUN__API]]
"""

##

[[stack]]
name = "umami"
tags = ["apps", "analytics", "public"]
deploy = true
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["umami.yaml"]
environment = """
UMAMI_APP_SECRET=[[UMAMI__SECRET]]
UMAMI_DB_PASSWORD=[[UMAMI__POSTGRES]]
"""

##

[[repo]]
name = "stacks"
[repo.config]
server = "pbox"
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/stacks"

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true }
]

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server = "pbox"

##

[[resource_sync]]
name = "stacks"
[resource_sync.config]
repo = "cwelsys/stacks"
git_account = "cwelsys"
resource_path = ["sync.toml"]
managed = true