###################################
# 🦎 KOMODO COMPOSE - POSTGRES 🦎 #
###################################

## This compose file will deploy:
##   1. Postgres + FerretDB Mongo adapter (https://www.ferretdb.com)
##   2. Komodo Core
##   3. Komodo Periphery
include:
  - ../pbox.yaml
volumes:
  repo-cache:
    external: true
  kmongo-db:
    external: true
  kmongo-cfg:
    external: true

services:
  mongo:
    image: mongo
    container_name: komo-mongo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      docker-volume-backup.stop-during-backup: true
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
      - stack
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 27017:27017
    volumes:
      - kmongo-db:/data/db
      - kmongo-cfg:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo
    labels:
      - komodo.skip
      # Public route - only for the /listener path
      - traefik.enable=true
      - traefik.http.routers.komodo-public.rule=Host(`komo.cwel.sh`) && PathPrefix(`/listener`)
      - traefik.http.routers.komodo-public.service=komodo
      - traefik.http.services.komodo.loadbalancer.server.port=9120
      - traefik.docker.network=public
      - kop.namespace=public

      # Internal route - for everything else
      - traefik.http.routers.komodo-internal.rule=Host(`k.cwel.sh`)
      - traefik.http.routers.komodo-internal.service=komodo
      - traefik.docker.network=internal

      # Homepage config
      - homepage.name=Komodo
      - homepage.icon=komodo.png
      - homepage.group=Management
      - homepage.description=Docker ops
      - homepage.href=https://k.cwel.sh
    restart: unless-stopped
    networks:
      - public
      - internal
      - stack
    depends_on:
      - mongo
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    ports:
      - 9120:9120
    env_file: ./.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - repo-cache:/repo-cache
    extra_hosts:
      - host.docker.internal:host-gateway
