services:
  ferretdb:
    env_file: ./.env
    image: ghcr.io/ferretdb/ferretdb:1
    container_name: ferretdb
    labels:
      - 'komodo.skip'
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    networks:
      - pbox
    # ports:
    #   - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:${KOMODO_DB_PASSWORD}@postgres:5432/komodo

  core:
    env_file: ./.env
    image: ghcr.io/moghtech/komodo-core:1.17.0
    container_name: komodo
    labels:
      - komodo.skip
      - traefik.enable=true
      - traefik.http.routers.komodo.rule=Host(`komo.cwel.sh`)
      - traefik.http.routers.komodo.tls.certresolver=le
      - traefik.http.routers.komodo.entrypoints=https
      - traefik.http.services.komodo.loadbalancer.server.port=9120
      - homepage.name=Komodo
      - homepage.icon=komodo.png
      - homepage.group=System
      - homepage.description=Docker ops
      - homepage.href=http://komo.cwel.sh
      - homepage.statusStyle=dot
    restart: unless-stopped
    depends_on:
      - ferretdb
    networks:
      - pbox
      - proxy
    ports:
      - 9120:9120
    # environment:
    #   KOMODO_DATABASE_URI: mongodb://postgres:${KOMODO_DB_PASSWORD}@ferretdb:27017/${KOMODO_DATABASE_DB_NAME:-komodo}?authMechanism=PLAIN&tls=false

    volumes:
      ## Core cache for repos for latest commit hash / contents
      - repo-cache:/repo-cache
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      # - ./core.toml:/config/config.toml
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  repo-cache:
networks:
  pbox:
    external: true
    name: 'pbox'
  proxy:
    external: true
