###################################
# 🦎 KOMODO COMPOSE - POSTGRES 🦎 #
###################################

## This compose file will deploy:
##   1. Postgres + FerretDB Mongo adapter (https://www.ferretdb.com)
##   2. Komodo Core
##   3. Komodo Periphery

services:
  postgres:
    image: postgres:17
    container_name: pg-komodo
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    networks:
      - internal
    restart: unless-stopped
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${KOMODO_DB_USERNAME}
      - POSTGRES_PASSWORD=${KOMODO_DB_PASSWORD}
      - POSTGRES_DB=${KOMODO_DATABASE_DB_NAME:-komodo}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KOMODO_DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:1
    container_name: ferretdb
    networks:
      - internal
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    # ports:
    #   - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/${KOMODO_DATABASE_DB_NAME:-komodo}

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo
    labels:
      - komodo.skip
      # - traefik.enable=true
      # - traefik.http.routers.komodo.rule=Host(`komo.cwel.sh`)
      # - traefik.http.routers.komodo.tls.certresolver=le
      # - traefik.http.routers.komodo.entrypoints=https
      # - traefik.http.services.komodo.loadbalancer.server.port=9120
      # - homepage.name=Komodo
      # - homepage.icon=komodo.png
      # - homepage.group=System
      # - homepage.description=Docker ops
      # - homepage.href=http://komo.cwel.sh
      # - homepage.statusStyle=dot
    restart: unless-stopped
    networks:
      - proxy
      - internal
    depends_on:
      - ferretdb
    logging:
      driver: ${COMPOSE_LOGGING_DRIVER:-local}
    ports:
      - 9120:9120
    env_file: ./.env
    environment:
      KOMODO_DATABASE_URI: mongodb://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@ferretdb:27017/${KOMODO_DATABASE_DB_NAME:-komodo}?authMechanism=PLAIN
    volumes:
      - repo-cache:/repo-cache
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  repo-cache:
  pg-data:
networks:
  proxy:
    external: true
  internal:
    external: true
