accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  filters:
    statusCodes:
      - "200-299" # log successful http requests
      - "400-599" # log failed http requests
  # collect logs as in-memory buffer before writing into log file
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings
api:
  dashboard: true
  insecure: true
metrics:
  influxDB2:
     address: http://influxdb2:8086
     token: {{INFLUXDB_TOKEN}}
     org: influx-org
     bucket: influx-bucket
     addEntryPointsLabels: true
     addRoutersLabels: true
     addServicesLabels: true
     pushInterval: 60s
     additionalLabels:
       instance: internal
providers:
  docker:
    exposedByDefault: false
  redis:
    endpoints:
      - int-redis:6379
  file:
    directory: /config/dynamic
    watch: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    asDefault: true
    address: :443
    http:
      middlewares:
       - security-headers@file
       - rate-limit@file
      tls:
        certResolver: internalresolver
        domains:
          - main: cwel.sh
            sans:
              - "*.cwel.sh"

certificatesResolvers:
  internalresolver:
    acme:
      email: "info@cwel.sh"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
log:
  level: info

experimental:
  plugins:
    cache:
      moduleName: "github.com/iamolegga/plugin-simplecache"
      version: "v0.3.0"
