services:
  osx:
    container_name: osx
    image: sickcodes/docker-osx
    restart: unless-stopped
    # dns:
    #   - 1.1.1.1
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - 5999:5999
      - 1234:1234
      - 50922:10022
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/lib/libvirt/images/maindisk.qcow2:/image
      - /var/lib/libvirt/images/bootdisk.qcow2:/bootdisk
    environment:
      - IMAGE_PATH=/image
      - BOOTDISK=/bootdisk
      - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=${VNCPASS}
      - DISPLAY=:99
      - WIDTH=1920
      - HEIGHT=1080
      - SHORTNAME=ventura
      - NOPICKER=true
      - ADDITIONAL_PORTS=hostfwd=tcp::1234-:1234,
