services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    # devices:
    #   - /path/to/device:/path/to/device
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8123']
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`ass.cwel.sh`)
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=le
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      # - traefik.http.middlewares.secHeaders.headers.browserXssFilter=true
      # - traefik.http.middlewares.secHeaders.headers.contentTypeNosniff=true
      # - traefik.http.middlewares.secHeaders.headers.frameDeny=true
      # - traefik.http.middlewares.secHeaders.headers.sslRedirect=true
      # - traefik.http.middlewares.secHeaders.headers.stsIncludeSubdomains=true
      # - traefik.http.middlewares.secHeaders.headers.stsPreload=true
      # - traefik.http.middlewares.secHeaders.headers.stsSeconds=31536000
      # - traefik.http.middlewares.secHeaders.headers.customFrameOptionsValue=SAMEORIGIN
      # - traefik.http.routers.homeassistant.middlewares=secHeaders
      - homepage.group=Apps
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.png
      - homepage.href=https://ass.cwel.sh
      - homepage.description=Open source home automation that puts local control and privacy first
      - homepage.weight=3
      - homepage.widget.type=homeassistant
      - homepage.widget.url=https://ass.cwel.sh
      - homepage.widget.key=${ACCESS_TOKEN}
