---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks/

- Bookmarks:
    - Github:
        - href: https://github.com/
          icon: /images/github.png

    - YouTube:
        - href: https://youtube.com/
          icon: /images/youtube.png

    - Drive:
        - href: https://drive.proton.me/u/0/
          icon: /images/proton-drive.png

    - Code Server:
        - href: https://code.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/vscode.png

    - Linkding:
        - href: https://linkding.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/linkding.png

    - Resume:
        - icon: reactive-resume.png
          href: https://resume.{{HOMEPAGE_VAR_DOMAIN_NAME}}/

    - Umami:
        - href: https://umami.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/umami.png

    - IT-Tools:
        - href: https://tools.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/it-tools.png

    - Nessus:
        - href: https://pbox:8834/
          icon: /images/nessus.jpg

    - pstick:
        - href: http://pstick:9090
          icon: /images/cockpit.png

    - Monkeytype:
        - href: https://monkey.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/monkeytype.png

    - Apollo:
        - href: https://wini:47990/
          icon: /images/sunshine.png

    - recommendarr:
        - href: https://recommendarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: /images/recommendarr.png

    - profilarr:
        - href: https://profilarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: mdi-docker

    - maintainerr:
        - href: https://maintainerr.{{HOMEPAGE_VAR_DOMAIN_NAME}}/
          icon: maintainerr.png
