---
# For configuration options and examples, please see:
# https://gethomepage.dev/widgets/

- logo:
    icon: /images/logo.png

- greeting:
    text_size: md
    text: Sup Ma'

- glances:
    url: http://192.168.4.89:61208
    version: 4
    cpu: true
    mem: true
    disk:
      - /
      - /mnt/cache/cache1
      - /mnt/media
      - /mnt/bool
      - /mnt/backup

- datetime:
    text_size: sm
    locale: us
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: 'America/New_York'

- openmeteo:
    label: {{HOMEPAGE_VAR_LOCATION}}
    latitude: {{HOMEPAGE_VAR_LAT}}
    longitude: {{HOMEPAGE_VAR_LONG}}
    timezone: America/New_York
    units: imperial
    cache: 5
