#for initialization of osx container

services:
  osx:
    container_name: osx
    image: sickcodes/docker-osx
    dns:
      - 1.1.1.1
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - 5999:5999
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/lib/libvirt/images/maindisk.qcow2:/image
    environment:
      - SHORTNAME=ventura
      - IMAGE_PATH=/image
      - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=osx
      - DISPLAY=:99
      - WIDTH=1920
      - HEIGHT=1080
      - GENERATE_UNIQUE=true
