volumes:
  gitea:
    external: true
  git-db:
    external: true
  git-runner:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=git-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GIT_PG_PASS}
    expose:
      - 3000
      - 22
    volumes:
      - gitea:/data
      - ${CONFIGDIR}/gitea/app.ini:/data/gitea/conf/app.ini:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
     - internal
     - gitea
    labels:
     - traefik.enable=true
     - traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)
     - traefik.http.services.gitea.loadbalancer.server.port=3000
     - traefik.docker.network=internal

  git-db:
    container_name: git-db
    image: docker.io/library/postgres:14
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GIT_PG_PASS}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - git-db:/var/lib/postgresql/data

  runner:
    image: gitea/act_runner:0.2.11
    container_name: gitea-runner
    restart: always
    networks:
      - gitea
    depends_on:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/gitea/config.yaml:/config.yaml
      - git-runner:/data
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=https://git.${DOMAIN}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=atlas
