volumes:
  gitea:
    external: true
  git-db:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GIT_PG_PASS}
    expose:
      - 3000
      - 22
    volumes:
      - gitea:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
     - internal
     - stack
    labels:
     - traefik.enable=true
     - traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)
     - traefik.http.services.gitea.loadbalancer.server.port=3000
     - traefik.docker.network=internal

  git-db:
    container_name: git-db
    image: docker.io/library/postgres:14
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GIT_PG_PASS}
      - POSTGRES_DB=gitea
    networks:
      - stack
    volumes:
      - git-db:/var/lib/postgresql/data
