[[server]]
name = "pbox"
[server.config]
enabled = true
cpu_warning = 92.0
disk_warning = 80.0

##

[[stack]]
name = "arr"
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media/process"
file_paths = [
  "../../pbox.yaml",
  "arr.yaml",
  "exportarr.yaml"
]
environment = """
SONARR_API_KEY=[[SONARR__API]]
RADARR_API_KEY=[[RADARR__API]]
LIDARR_API_KEY=[[LIDARR__API]]
PROWLARR_API_KEY=[[PROWLARR__API]]
WHISPARR_API_KEY=[[WHISPARR__API]]
SABNZBD_API_KEY=[[SABNZBD__API]]
QBIT_PASSWORD=[[QBITTORRENT__PASSWORD]]
"""

##

[[stack]]
name = "auth"
[stack.config]
server = "pbox"
poll_for_updates = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network/auth"
file_paths = [
  "../../pbox.yaml",
  "authentik.yaml"
]
environment = """
PG_PASS=[[AUTHENTIK__POSTGRES]]
AUTHENTIK_SECRET_KEY=[[AUTHENTIK__KEY]]
OUTPOST_TOKEN=[[AUTHENTIK__OUTPOST]]
SMTPHOST=in-v3.mailjet.com
SMTPUSER=[[SMTP__USER]]
SMTPASS=[[SMTP__PASSWORD]]
"""

##

[[stack]]
name = "dash"
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = ["../pbox.yaml", "homepage.yaml"]
environment = """
OPENWEATHERMAP_TOKEN=[[OPENWEATHERMAP__API]]
HP_LOC_LABEL=[[HOMEPAGE__LOCATION]]
HP_LOC_LAT=[[HOMEPAGE__LAT]]
HP_LOC_LONG=[[HOMEPAGE__LONG]]
TS_API=[[TAILSCALE__API]]
CLOUDFLARE_API=[[CLOUDFLARE__API]]
CLOUDFLARE_ACC_ID=[[CLOUDFLARE__ACCOUNT]]
TUNNEL_ID=[[CLOUDFLARE__TUNNEL_ID]]
CROWDSEC_PASS=[[CROWDSEC__API]]
SONARR_API_KEY=[[SONARR__API]]
RADARR_API_KEY=[[RADARR__API]]
LIDARR_API_KEY=[[LIDARR__API]]
WHISPARR_API_KEY=[[WHISPARR__API]]
PROWLARR_API_KEY=[[PROWLARR__API]]
BAZARR_API_KEY=[[BAZARR__API]]
JELLYSEERR_API_KEY=[[JELLYSEERR__API]]
QBITTORRENT_PASSWORD=[[QBITTORRENT__PASSWORD]]
TAUTULLI_API_KEY=[[TAUTULLI__API]]
SPEED_API=[[SPEEDTEST__API]]
PLEX_API_KEY=[[PLEX__API]]
SABNZBD_API_KEY=[[SABNZBD__API]]
PROTON_ICAL=[[PROTON__ICAL]]
AUTHENTIK_API=[[AUTHENTIK__API]]
FINNHUB_TOKEN=[[FINNHUB__API]]
CALIBRE_PASS=[[CALIBRE__PASSWORD]]
GLUETUN_API_KEY=[[GLUETUN__API]]
HOMEASS_API_KEY=[[HOMEASSISTANT__API]]
GRAFANA_PASS=[[GRAFANA__API]]
JELLYFIN_API_KEY=[[JELLYFIN__API]]
STASH_API_KEY=[[STASH__API]]
TECHNITIUM_API_KEY=[[TECHNITIUM__API]]
IMMICH_API_KEY=[[IMMICH__API]]
MEALIE_API_KEY=[[MEALIE__API]]
BESZEL_PW=[[BESZEL__PASSWORD]]
NEXTCLOUD_PW=[[NEXTCLOUD__PASSWORD]]
NEXTCLOUD_API_KEY=[[NEXTCLOUD__TOKEN]]
GITEA_API_KEY=[[GIT__PAT]]
NEXTDNS_API_KEY=[[NEXTDNS__API]]
KOMO_API_KEY=[[KOMODO__API]]
KOMO_API_SECRET=[[KOMODO__API_SECRET]]
FRESHRSS_API_KEY=[[FRESHRSS__API]]
AUTOBRR_API_KEY=[[AUTOBRR__API]]
STEAMGRID_API_KEY=[[STEAMGRID__API]]
KAVITA_API_KEY=[[KAVITA__API]]
ABS_API_KEY=[[AUDIOBOOKSHELF__API]]
READARR_API_KEY=[[READARR__API]]
"""

##

[[stack]]
name = "discord"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps/discord"
file_paths = [
  "../../pbox.yaml",
  "ipmap.yaml",
  "membarr.yaml",
  "muse.yaml",
  "redbot.yaml",
  "requestarr.yaml"
]
environment = """
GOOGLE_API=[[GOOGLE__API]]
GEOAPIFY_API=[[GEOAPIFY__API]]
REDBOT_TOKEN=[[DISCORD__REDBOT]]
MUSE_TOKEN=[[DISCORD__MUSE]]
MEMBARR_TOKEN=[[DISCORD__MEMBARR]]
DOPLARR_TOKEN=[[DISCORD__DOPLARR]]
JELLYSEERR_API_KEY=[[JELLYSEERR__API]]

"""

##

[[stack]]
name = "downs"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media/process"
file_paths = [
  "../../pbox.yaml",
  "metube.yaml",
  "sab.yaml",
  "tortun.yaml"
]
environment = """
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD=[[QBITTORRENT__PASSWORD]]
SABNZBD_API_KEY=[[SABNZBD__API]]
WIREGUARD_PRIVATE_KEY=[[PROTON__WIREGUARD]]
GLUETUN_APIKEY=[[GLUETUN__API]]
"""

##

[[stack]]
name = "media"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "media/consume"
file_paths = [
  "../../pbox.yaml",
  "book.yaml",
  "immich.yaml",
  "jellyfin.yaml",
  "stash.yaml"
]
environment = """
ROMM_AUTH=[[ROMM__AUTH]]
MARIADB_PW=[[ROMM__MARIADB]]
ROMM_DB_PW=[[ROMM__ROMMDB]]
IGDB_CLIENT_ID=[[ROMM__IGDB_ID]]
IGDB_CLIENT_SECRET=[[ROMM__IGDB_SECRET]]
IMMICH_PG_PASS=[[IMMICH__POSTGRES]]
STEAMGRID_API_KEY=[[STEAMGRID__API]]
HARDCOVER_TOKEN=[[CALIBRE__HCAPI]]
"""

##

[[stack]]
name = "monitor"
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "monitor"
file_paths = [
  "../pbox.yaml",
  "beszel.yaml",
  "dozzle.yaml",
  "grafana.yaml",
  "influx.yaml",
  "scrutiny.yaml",
  "speed.yaml",
  "umami.yaml"
]
environment = """
INFLUXDB_PASS=[[TRAEFIK__INFLUXDB_PASS]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
BESZEL_KEY=[[BESZEL__KEY]]
SPEED_API=[[SPEEDTEST__API]]
UMAMI_APP_SECRET=[[UMAMI__SECRET]]
UMAMI_DB_PASSWORD=[[UMAMI__POSTGRES]]
"""

##

[[stack]]
name = "proxy"
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network/proxy"
file_paths = [
  "../../pbox.yaml",
  "external.yaml",
  "internal.yaml",
  "kop.yaml"
]
environment = """
CF_DNS_API_TOKEN=[[CLOUDFLARE__API]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
CF_TRAEFIK_TUNNEL_TOKEN=[[CLOUDFLARE__TUNNEL]]
CS_TRAEFIK_BOUNCER_KEY=[[CROWDSEC__BOUNCER]]
BOUNCER_HOST=crowdsec:8080

"""

##

[[stack]]
name = "services"
[stack.config]
server = "pbox"
poll_for_updates = true
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "apps"
file_paths = [
  "../pbox.yaml",
  "cloud.yaml",
  "monkey.yaml"
]
environment = """
SMTP_USER=[[SMTP__USER]]
SMTP_PASS=[[SMTP__PASSWORD]]
SMTP_HOST=in-v3.mailjet.com
RX_PG_PASS=[[RXRESUME__POSTGRES]]
MINIO_PW=[[RXRESUME__MINIO]]
RX_SECRET=[[RXRESUME__SECRET]]
RX_REFRESH_SECRET=[[RXRESUME__REFRESH]]
CHROME_TOKEN=[[RXRESUME__CHROME]]
"""

##

[[stack]]
name = "ts-utils"
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "utils"
file_paths = ["../pbox.yaml", "tailscale.yaml"]
environment = """
TS_AUTHKEY=[[TAILSCALE__SOCKET]]
OP_ACCESS_TOKEN=[[OP__ACCESS_TOKEN]]
KOMO_API_KEY=[[KOMODO__API]]
KOMO_API_SECRET=[[KOMODO__API_SECRET]]
OP_VAULT_UUID=[[OP__UUID]]
"""

##

[[stack]]
name = "utils"
[stack.config]
server = "pbox"
auto_update = true
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "utils"
file_paths = [
  "../pbox.yaml",
  "backrest.yaml",
  "filebrowser.yaml",
  "ftp.yaml",
  "it-tools.yaml",
  "linkding.yaml",
  "rdesk.yaml"
]
environment = """
SFTPGO_DB_PASS=[[SFTPGO__PASSWORD]]
"""

##

[[build]]
name = "ipmap"
[build.config]
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/ipmap"

##

[[build]]
name = "komodo-op"
[build.config]
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/komodo-op"
image_registry = [{  }]

##

[[build]]
name = "ownfoil"
[build.config]
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/ownfoil"

##

[[repo]]
name = "stacks"
[repo.config]
server = "pbox"
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/stacks"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "pbox"

##

[[resource_sync]]
name = "stacks"
[resource_sync.config]
repo = "cwelsys/stacks"
git_account = "cwelsys"
resource_path = [".komodo/sync.toml"]
managed = true