[[server]]
name = "pbox"
[server.config]
address = "https://host.docker.internal:8120"
enabled = true

##

[[stack]]
name = "arr"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/process"
file_paths = ["arr.yaml", "../../pbox.yaml"]
environment = """
SONARR_API_KEY=[[SONARR__API]]
RADARR_API_KEY=[[RADARR__API]]
LIDARR_API_KEY=[[LIDARR__API]]
WHISPARR_API_KEY=[[WHISPARR__API]]
READARR_API_KEY=[[READARR__API]]
QBITTORRENT_PASSWORD=[[QBITTORRENT__PASSWORD]]
"""

##

[[stack]]
name = "auth"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "network/auth"
file_paths = [
  "authentik.yaml",
  "../../pbox.yaml"
]
environment = """
PG_PASS=[[AUTHENTIK__POSTGRES]]
AUTHENTIK_SECRET_KEY=[[AUTHENTIK__KEY]]
OUTPOST_TOKEN=[[AUTHENTIK__OUTPOST]]
SMTPHOST=in-v3.mailjet.com
SMTPUSER=[[SMTP__USER]]
SMTPASS=[[SMTP__PASSWORD]]
"""

##

[[stack]]
name = "backrest"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "core"
file_paths = ["backrest.yaml", "../pbox.yaml"]

##

[[stack]]
name = "calibre"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/process"
file_paths = [
  "calibre.yaml",
  "../../pbox.yaml"
]

##

[[stack]]
name = "cloud"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/consume"
file_paths = [
  "nextcloud.yaml",
  "../../pbox.yaml"
]
environment = """
NC_PG_PASS=[[NEXTCLOUD__POSTGRES]]
REDIS_PASSWORD=[[NEXTCLOUD__REDIS]]
NC_ADMIN_USER_PASSWORD=[[NEXTCLOUD__PASSWORD]]
"""

##

[[stack]]
name = "code"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = [
  "codeserver.yaml",
  "../pbox.yaml"
]

##

[[stack]]
name = "dash"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "core"
file_paths = ["homepage.yaml", "../pbox.yaml"]
environment = """
OPENWEATHERMAP_TOKEN=[[OPENWEATHERMAP__API]]
TS_API=[[TAILSCALE__API]]
CLOUDFLARE_API=[[CLOUDFLARE__API]]
CLOUDFLARE_ACC_ID=[[CLOUDFLARE__ACCOUNT]]
TUNNEL_ID=[[CLOUDFLARE__TUNNEL_ID]]
CROWDSEC_PASS=[[CROWDSEC__API]]
SONARR_API_KEY=[[SONARR__API]]
RADARR_API_KEY=[[RADARR__API]]
LIDARR_API_KEY=[[LIDARR__API]]
WHISPARR_API_KEY=[[WHISPARR__API]]
PROWLARR_API_KEY=[[PROWLARR__API]]
OVERSEERR_API_KEY=[[OVERSEERR__API]]
READARR_API_KEY=[[READARR__API]]
QBITTORRENT_PASSWORD=[[QBITTORRENT__PASSWORD]]
TAUTULLI_API_KEY=[[TAUTULLI__API]]
SPEED_API=[[SPEEDTEST__API]]
PLEX_API_KEY=[[PLEX__API]]
SABNZBD_API_KEY=[[SABNZBD__API]]
PROTON_ICAL=[[PROTON__ICAL]]
AUTHENTIK_API=[[AUTHENTIK__API]]
FINNHUB_TOKEN=[[FINNHUB__API]]
CALIBRE_PASS=[[CALIBRE__PASSWORD]]
GLUETUN_API_KEY=[[GLUETUN__API]]
HOMEASS_API_KEY=[[HOMEASSISTANT__API]]
GRAFANA_PASS=[[GRAFANA__API]]
JELLYFIN_API_KEY=[[JELLYFIN__API]]
STASH_API_KEY=[[STASH__API]]
TECHNITIUM_API_KEY=[[TECHNITIUM__API]]
IMMICH_API_KEY=[[IMMICH__API]]
MEALIE_API_KEY=[[MEALIE__API]]
BESZEL_PW=[[BESZEL__PASSWORD]]
NEXTCLOUD_PW=[[NEXTCLOUD__PASSWORD]]
GITEA_API_KEY=[[GIT__PAT]]
KOMO_API_KEY=[[KOMODO__API]]
KOMO_API_SECRET=[[KOMODO__API_SECRET]]
FRESHRSS_API_KEY=[[FRESHRSS__API]]
"""

##

[[stack]]
name = "discord"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "discord"
file_paths = [
  "redbot.yaml",
  "muse.yaml",
  "doplarr.yaml",
  "membarr.yaml",
  "../pbox.yaml"
]
environment = """
GOOGLE_API=[[GOOGLE__API]]
REDBOT_TOKEN=[[DISCORD__REDBOT]]
MUSE_TOKEN=[[DISCORD__MUSE]]
MEMBARR_TOKEN=[[DISCORD__MEMBARR]]
DOPLARR_TOKEN=[[DISCORD__DOPLARR]]
OVERSEERR_API_KEY=[[OVERSEERR__API]]

"""

##

[[stack]]
name = "dns"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network"
file_paths = ["dns.yaml", "../pbox.yaml"]

##

[[stack]]
name = "downs"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/process"
file_paths = [
  "tortun.yaml",
  "sab.yaml",
  "../../pbox.yaml"
]
environment = """
QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD=[[QBITTORRENT__PASSWORD]]
SABNZBD_API_KEY=[[SABNZBD__API]]
WIREGUARD_PRIVATE_KEY=[[PROTON__WIREGUARD]]
GLUETUN_APIKEY=[[GLUETUN__API]]
"""

##

[[stack]]
name = "external"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network/proxy"
file_paths = [
  "external.yaml",
  "../../pbox.yaml"
]
environment = """
CF_DNS_API_TOKEN=[[CLOUDFLARE__API]]
CF_TRAEFIK_TUNNEL_TOKEN=[[CLOUDFLARE__TUNNEL]]
CS_TRAEFIK_BOUNCER_KEY=[[CROWDSEC__BOUNCER]]
BOUNCER_HOST=crowdsec:8080
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
"""

##

[[stack]]
name = "git"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "core"
file_paths = ["gitea.yaml", "../pbox.yaml"]
environment = """
GIT_PG_PASS=[[GITEA__POSTGRES]]
GITEA_RUNNER_TOKEN=[[GITEA__RUNNER]]
"""

##

[[stack]]
name = "immich"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/consume"
file_paths = ["immich.yaml", "../../pbox.yaml"]
environment = """
DB_PASSWORD=[[IMMICH__POSTGRES]]
UPLOAD_LOCATION=/mnt/media/image
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/opt/docker/immich-db
"""

##

[[stack]]
name = "internal"
[stack.config]
server = "pbox"
git_account = "cwelsys"
repo = "cwelsys/stacks"
run_directory = "network/proxy"
file_paths = [
  "internal.yaml",
  "../../pbox.yaml"
]
environment = """
CF_DNS_API_TOKEN=[[CLOUDFLARE__API]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
"""

##

[[stack]]
name = "it-tools"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["it-tools.yaml", "../pbox.yaml"]

##

[[stack]]
name = "kop"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "network/proxy"
file_paths = ["kop.yaml", "../../pbox.yaml"]

##

[[stack]]
name = "linkding"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["linkding.yaml", "../pbox.yaml"]

##

[[stack]]
name = "mealie"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["mealie.yaml", "../pbox.yaml"]

##

[[stack]]
name = "media"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "media/consume"
file_paths = [
  "plex.yaml",
  "jellyfin.yaml",
  "stash.yaml",
  "freshrss.yaml",
  "romm.yaml",
  "../../pbox.yaml"
]
environment = """
ROMM_AUTH=[[ROMM__AUTH]]
MARIADB_PW=[[ROMM__MARIADB]]
ROMM_DB_PW=[[ROMM__ROMMDB]]
IGDB_CLIENT_ID=[[ROMM__IGDB_ID]]
IGDB_CLIENT_SECRET=[[ROMM__IGDB_SECRET]]
"""

##

[[stack]]
name = "monitoring"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "monitor"
file_paths = [
  "grafana.yaml",
  "scrutiny.yaml",
  "dozzle.yaml",
  "../pbox.yaml",
  "beszel.yaml"
]
environment = """
INFLUXDB_PASS=[[TRAEFIK__INFLUXDB_PASS]]
INFLUXDB_TOKEN=[[TRAEFIK__INFLUXDB_TOKEN]]
BESZEL_KEY=[[BESZEL__KEY]]
"""

##

[[stack]]
name = "monkeytype"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["monkey.yaml", "../pbox.yaml"]

##

[[stack]]
name = "netdata"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "monitor"
file_paths = ["netdata.yaml", "../pbox.yaml"]

##

[[stack]]
name = "op-sync"
[stack.config]
server = "pbox"
project_name = "secrets"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = ".komodo/secrets"

##

[[stack]]
name = "posio"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["posio.yaml", "../pbox.yaml"]

##

[[stack]]
name = "proton-bridge"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "core"
file_paths = ["protonb.yaml", "../pbox.yaml"]

##

[[stack]]
name = "resume"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "apps"
file_paths = ["rxresume.yaml", "../pbox.yaml"]
environment = """
SMTP_USER=[[SMTP__USER]]
SMTP_PASS=[[SMTP__PASSWORD]]
SMTP_HOST=in-v3.mailjet.com
RX_PG_PASS=[[RXRESUME__POSTGRES]]
MINIO_PW=[[RXRESUME__MINIO]]
RX_SECRET=[[RXRESUME__SECRET]]
RX_REFRESH_SECRET=[[RXRESUME__REFRESH]]
CHROME_TOKEN=[[RXRESUME__CHROME]]
"""

##

[[stack]]
name = "tailsocket"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "core"
file_paths = ["ts-socket.yaml", "../pbox.yaml"]
environment = """
TS_AUTHKEY=[[TAILSCALE__SOCKET]]


"""

##

[[stack]]
name = "web"
[stack.config]
server = "pbox"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"
run_directory = "monitor"
file_paths = ["umami.yaml", "../pbox.yaml"]
environment = """
APP_SECRET=[[UMAMI__SECRET]]
UMAMI_DB_PASSWORD=[[UMAMI__POSTGRES]]
"""

##

[[build]]
name = "komodo-op"
[build.config]
builder = "local"
git_account = "cwelsys"
repo = "cwelsys/komodo-op"

##

[[repo]]
name = "stacks"
[repo.config]
server = "pbox"
builder = "local"
git_provider = "git.cwel.sh"
git_account = "cwel"
repo = "cwel/stacks"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "pbox"

##

[[resource_sync]]
name = "stacks"
[resource_sync.config]
git_provider = "git.cwel.sh"
repo = "cwel/stacks"
git_account = "cwel"
resource_path = [".komodo/sync.toml"]
managed = true