services:
  ext-kop:
    container_name: ext-kop
    image: ghcr.io/jittering/traefik-kop:latest
    restart: unless-stopped
    environment:
      - 'REDIS_ADDR=ext-redis:6379'
      - 'NAMESPACE=public'
      - 'DOCKER_HOST=tcp://kop-sockp:2375'
      - 'KOP_HOSTNAME=pbox-public'
      - 'BIND_IP=192.168.4.89'
    depends_on:
      - kop-sockp
    networks:
      - kop
      - stack
  int-kop:
    container_name: int-kop
    image: ghcr.io/jittering/traefik-kop:latest
    restart: unless-stopped
    environment:
      - 'REDIS_ADDR=int-redis:6379'
      - 'DOCKER_HOST=tcp://kop-sockp:2375'
      - 'KOP_HOSTNAME=pbox-internal'
      - 'BIND_IP=192.168.4.89'
    depends_on:
      - kop-sockp
    networks:
      - kop
      - stack
  kop-sockp:
    container_name: kop-sockp
    image: lscr.io/linuxserver/socket-proxy:latest
    networks:
      - stack
    environment:
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
      - POST=0
      - SERVICES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    restart: always
    read_only: true
    tmpfs:
      - /run
