services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: sonarr-exporter
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://sonarr:8989"
      APIKEY: ${SONARR_API_KEY}
    networks:
      - media
      - monitor
    ports:
      - "9707:9707"
    restart: unless-stopped
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: radarr-exporter
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: "http://radarr:7878"
      APIKEY: ${RADARR_API_KEY}
    networks:
      - media
      - monitor
    ports:
      - "9708:9708"
    restart: unless-stopped
  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: lidarr-exporter
    command: ["lidarr"]
    environment:
      PORT: 9709
      URL: "http://lidarr:8686"
      APIKEY: ${LIDARR_API_KEY}
    networks:
      - media
      - monitor
    ports:
      - "9709:9709"
    restart: unless-stopped
  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: prowlarr-exporter
    command: ["prowlarr"]
    environment:
      PORT: 9710
      URL: "http://prowlarr:9696"
      APIKEY: ${PROWLARR_API_KEY}
      PROWLARR__BACKFILL: true
      PROWLARR__BACKFILL_SINCE_DATE: "2025-01-01"
    networks:
      - media
      - monitor
    ports:
     - "9710:9710"
    restart: unless-stopped
  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: sabnzbd-exporter
    command: ["sabnzbd"]
    environment:
      PORT: 9711
      URL: "http://sabnzbd:8080"
      APIKEY: ${SABNZBD_API_KEY}
    networks:
      - media
      - monitor
    ports:
     - "9711:9711"
    restart: unless-stopped
  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: bazarr-exporter
    command: ["bazarr"]
    environment:
      PORT: 9712
      URL: "http://bazaar:6767"
    networks:
      - media
      - monitor
    ports:
      - "9712:9712"
    restart: unless-stopped
  readarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: readarr-exporter
    command: ["readarr"]
    environment:
      PORT: 9713
      URL: "http://readarr:8787"
      APIKEY: ${READARR_API_KEY}
    networks:
      - media
      - monitor
    ports:
      - "9713:9713"
    restart: unless-stopped
