services:
  ytptube:
    user: "1000:1001" 
    image: ghcr.io/arabcoders/ytptube:latest
    container_name: ytptube
    restart: unless-stopped
    networks:
      - internal
    # ports:
    #   - "8081:8081"
    volumes:
      - ${DOCKERM}/metube/config:/config:rw
      - ${RUST}/downloads:/downloads
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.metube.rule=Host(`tube.${DOMAIN}`)
      - traefik.http.services.metube.loadbalancer.server.port=8081
      - traefik.docker.network=internal
