services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/sabnzbd:/config
      - ${DOCKERM}/sabnzbd/custom:/custom-cont-init.d
      - ${RUST}:/data
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sab.${INTDOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      - internal
      - media
