services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/sabnzbd:/config
      - ${RUST}:/data
      - /opt/arrscripts/sab/custom-cont-init.d:/custom-cont-init.d
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      - internal
      - media
