services:
  sportyfin:
    image: sportyfin:latest
    pull_policy: never
    container_name: sportyfin
    user: '1000:1000'
    restart: "no"  # Run once to generate files
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/sportyfin:/sportyfin/output
    networks:
      - media
    command: ["python3", "-m", "sportyfin", "-a", "-v", "-d"]