services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    networks:
      - internal
      - media
    # ports:
    #   - 34400:34400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/threadfin/data/conf:/home/threadfin/conf
      - ${DOCKERM}/threadfin/data/temp:/tmp/threadfin:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.threadfin.rule=Host(`threadfin.${CASA}`)
      - traefik.docker.network=internal
      - traefik.http.services.threadfin.loadbalancer.server.port=34400
    restart: unless-stopped

  epg-scraper:
    build:
      context: https://github.com/iptv-org/epg.git
      dockerfile: Dockerfile
    container_name: epg-scraper
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CRON_SCHEDULE=0 6 * * *  # Daily at 6 AM
      - MAX_CONNECTIONS=5
      - GZIP=true
      - DAYS=7
      - TIMEOUT=10
      - DELAY=3
    volumes:
      - ${DOCKERM}/threadfin/epg:/epg/output
      - ${DOCKERM}/threadfin/epg/channels.xml:/epg/channels.xml
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.epg.rule=Host(`epg.${CASA}`)
      - traefik.docker.network=internal
      - traefik.http.services.epg.loadbalancer.server.port=3000
