volumes:
  sonarr:
    external: true
  radarr:
    external: true
  lidarr:
    external: true
  prowlarr:
    external: true
  overseerr:
    external: true
  maintainerr:
    external: true
  tautulli:
    external: true
  recommendarr:
    external: true
  readarr:
    external: true
  tdarr:
    external: true
  tdarr-cache:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - sonarr:/config
      - ${RUST}:/data
      - ${CONFIGDIR}/arr/sonarr/custom-services.d:/custom-services.d
      - ${CONFIGDIR}/arr/sonarr/custom-cont-init.d:/custom-cont-init.d
      - ${CONFIGDIR}/arr/sonarr/rconfig.yaml:/config/extended/rconfig.yaml
      - ${CONFIGDIR}/arr/sonarr/extended.conf:/config/extended.conf
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:8989/ping' ]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=https://sonarr.${DOMAIN}
      - homepage.description=TV Series management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API_KEY}
      - docker-volume-backup.stop-during-backup=true
    networks:
      - internal
      - media

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - radarr:/config
      - ${RUST}:/data
      - ${CONFIGDIR}/arr/radarr/custom-services.d:/custom-services.d
      - ${CONFIGDIR}/arr/radarr/custom-cont-init.d:/custom-cont-init.d
      - ${CONFIGDIR}/arr/radarr/rconfig.yaml:/config/extended/rconfig.yaml
      - ${CONFIGDIR}/arr/radarr/extended.conf:/config/extended.conf
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:7878/ping' ]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.${DOMAIN}
      - homepage.description=Movies management
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}
      - docker-volume-backup.stop-during-backup=true
    networks:
      - internal
      - media

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - lidarr:/config
      - ${RUST}:/data
      - ${CONFIGDIR}/arr/lidarr/custom-services.d:/custom-services.d
      - ${CONFIGDIR}/arr/lidarr/custom-cont-init.d:/custom-cont-init.d
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:8686/ping' ]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=https://lidarr.${DOMAIN}
      - homepage.description=Music management
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://lidarr:8686
      - homepage.widget.key=${LIDARR_API_KEY}
      - docker-volume-backup.stop-during-backup=true
    networks:
      - internal
      - media

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - readarr:/config
      - ${RUST}:/data
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:8787/ping' ]
      interval: 30s
      retries: 10
    restart: unless-stopped
    networks:
     - media
     - internal
    labels:
     - traefik.enable=true
     - traefik.docker.network=internal
     - traefik.http.routers.readarr.rule=Host(`readarr.${DOMAIN}`)
     - traefik.http.services.readarr.loadbalancer.server.port=8787
     - homepage.group=Media
     - homepage.name=Readarr
     - homepage.icon=readarr.png
     - homepage.href=https://readarr.${DOMAIN}
     - homepage.description=Books management
     - homepage.widget.type=readarr
     - homepage.widget.url=http://readarr:8787
     - homepage.widget.key=${READARR_API_KEY}
     - docker-volume-backup.stop-during-backup=true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - prowlarr:/config
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:9696/ping' ]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - homepage.group=Download
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.${DOMAIN}
      - homepage.description=Indexers management
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
      - docker-volume-backup.stop-during-backup=true
    networks:
      - internal
      - media

  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    restart: always
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191
    networks:
      - internal

  unpackerr:
    image: ghcr.io/unpackerr/unpackerr:latest
    container_name: unpackerr
    volumes:
      - ${RUST}/tor:/data/tor
    restart: always
    user: ${ID}:${ID}
    environment:
      - TZ=${TZ}
      - UN_SONARR_0_URL=http://sonarr:8989/
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://radarr:7878/
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
    security_opt:
      - no-new-privileges:true
    networks:
      - media

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - overseerr:/config
    restart: unless-stopped
    ports:
      - 5055:5055
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`req.${DOMAIN}`)
      - traefik.docker.network=public
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - kop.namespace=public
      - homepage.group=Media
      - homepage.name=Overseerr
      - homepage.icon=overseerr.png
      - homepage.href=https://req.${DOMAIN}
      - homepage.description=Requests management
      - docker-volume-backup.stop-during-backup=true
      # - homepage.widget.type=overseerr
      # - homepage.widget.url=http://overseerr:5055
      # - homepage.widget.key=${OVERSEERR_API_KEY}
    networks:
      - public
      - media

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest # or jorenn92/maintainerr:latest
    container_name: maintainerr
    user: ${ID}:${ID}
    networks:
      - internal
      - media
    volumes:
      - maintainerr:/opt/data
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.maintainerr.rule=Host(`maintainerr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.maintainerr.loadbalancer.server.port=6246
      - homepage.group=Media
      - homepage.name=Maintainerr
      - homepage.icon=maintainerr.png
      - homepage.href=https://maintainerr.${DOMAIN}
      - homepage.description=Library maintenance
      - docker-volume-backup.stop-during-backup=true

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
    volumes:
      - tautulli:/config
    networks:
      - internal
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=https://tautulli.${DOMAIN}
      - homepage.description=Plex monitoring and statistics
      - homepage.widget.type=tautulli
      - homepage.widget.url=http://tautulli:8181
      - homepage.widget.key=${TAUTULLI_API_KEY}

  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
      - NODE_ENV=production
      - DOCKER_ENV=false
      - PORT=3000
      - PUBLIC_URL=https://recommendarr.${DOMAIN}
      - FORCE_SECURE_COOKIES=true
    volumes:
      - recommendarr:/app/server/data
    restart: unless-stopped
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.recommendarr.rule=Host(`recommendarr.${DOMAIN}`)
      - traefik.docker.network=internal
      - traefik.http.services.recommendarr.loadbalancer.server.port=3000
      - homepage.group=Media
      - homepage.name=Recommendarr
      # - homepage.icon=recommendarr.png
      - homepage.href=https://recommendarr.${DOMAIN}
      - homepage.description=Media recommendations
      - docker-volume-backup.stop-during-backup=true

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - internal
      - media
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=${ID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=core
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - tdarr:/app
      - ${RUST}:/media
      - tdarr-cache:/temp
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.${DOMAIN}`)
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - traefik.docker.network=internal
      - homepage.group=Media
      - homepage.name=tdarr
      - homepage.icon=tdarr.png
      - homepage.href=https://tdarr.${DOMAIN}
      - homepage.description=Transcoding
      - docker-volume-backup.stop-during-backup=true
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=${ID}
      - UMASK_SET=002
      - nodeName=worker
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - tdarr:/app
      - tdarr-cache:/temp
      - ${RUST}:/media
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
