services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=claim-_55FFKBsr3sj3wtsUQML
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    restart: unless-stopped
    volumes:
      - plex-data:/config
      - ${RUST}/tv:/tv
      - ${RUST}/movie:/movie
      - ${RUST}/anime:/anime
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:32400/web/index.html']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.docker.network=internal
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://plex.${DOMAIN}
      - homepage.description=Media server
      - homepage.weight=-1
      - homepage.widget.type=plex
      - homepage.widget.url=http://plex:32400
      - homepage.widget.key=${PLEX_TOKEN}
    networks:
      - internal

  # jellyfin:
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   environment:
  #     - PUID=${ID}
  #     - PGID=${ID}
  #     - TZ=${TZ}
  #     - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
  #   volumes:
  #     - ${DOCKERDIR}/jellyfin:/config
  #     - ${RUST}:/data
  #   ports:
  #     - 8096:8096
  #     - 8920:8920 #optional
  #     - 7359:7359/udp #optional
  #     - 1901:1901/udp #optional
  #   restart: always
  #   healthcheck:
  #     test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8096/health']
  #     interval: 30s
  #     retries: 10
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
  #     - traefik.http.routers.jellyfin.tls=true
  #     - traefik.http.routers.jellyfin.tls.certresolver=le
  #     - traefik.http.services.jellyfin.loadbalancer.server.port=8096
  #     - homepage.group=Media
  #     - homepage.name=Jellyfin
  #     - homepage.icon=jellyfin.png
  #     - homepage.href=https://jellyfin.${DOMAIN}
  #     - homepage.description=Media server
  #     - homepage.weight=4
  #     - homepage.widget.type=jellyfin
  #     - homepage.widget.url=http://jellyfin:8096
  #     - homepage.widget.key=${JELLYFIN_API_KEY}
  #   networks:
  #     - proxy

volumes:
  plex_data:
