volumes:
  immich-ml:
    external: true
  immich-db:
    external: true

services:
  immich-server:
    image: altran1502/immich-server:${IMMICH_VERSION:-release}
    container_name: immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - TZ=${TZ}
      - REDIS_HOST=immich-redis
      - DB_HOSTNAME=immich-db
    expose:
      - 2283
    depends_on:
      - immich-redis
      - immich-db
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - internal
      - stack
    labels:
     - traefik.enable=true
     - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
     - traefik.http.services.immich.loadbalancer.server.port=2283
     - traefik.docker.network=internal

  immich-machine-learning:
    image: altran1502/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-ml
    volumes:
      - ${RUST}/image:/usr/src/app/upload
      - immich-ml:/cache
    environment:
      - NODE_ENV=production
      - TZ=${TZ}
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=immich
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - REDIS_HOST=immich-redis
      - DB_HOSTNAME=immich-db
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - internal
      - stack

  immich-redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: immich-redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - stack

  immich-db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    container_name: immich-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: unless-stopped
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    networks:
      - stack

