services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${ID}
      - PGID=${ID}
      - TZ=${TZ}
      - VERSION=docker
      # - PLEX_CLAIM=
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    restart: unless-stopped
    volumes:
      - plex-data:/config
      - ${RUST}/tv:/tv
      - ${RUST}/movie:/movie
      - ${RUST}/anime:/anime
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:32400/web/index.html' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.docker.network=internal
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=/images/plex3.png
      - homepage.href=https://plex.${DOMAIN}
      - homepage.description=Media server
      - homepage.weight=-1
      - homepage.widget.type=plex
      - homepage.widget.url=http://plex:32400
      - homepage.widget.key=${PLEX_TOKEN}
    networks:
      - internal
      - default

  plextraktsync:
    image: lscr.io/linuxserver-labs/plextraktsync:latest
    container_name: plextraktsync
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      - default
    volumes:
      - ${CONFIGDIR}/ptraktsync/config:/app/config
    environment:
      - PUID=1000
      - PGID=${ID}
      - TZ=${TZ}
  membarr:
    image: 'yoruio/membarr:latest'
    restart: unless-stopped
    container_name: membarr
    depends_on:
      - plex
    networks:
      - default
    volumes:
      - ${CONFIGDIR}/membarr/:/app/app/config
    environment:
      - token=${MEMBARR_TOKEN}

volumes:
  plex-data:
