volumes:
    stash:
      external: true
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    # ports:
    #   - "9999:9999"
    # network_mode: host
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/stash/generated/
      - STASH_METADATA=/stash/metadata/
      - STASH_CACHE=/stash/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGDIR}/media/stash:/root/.stash
      - stash:/stash
      - ${RUST}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.stash.rule=Host(`stash.cwel.sh`)
      - traefik.http.services.stash.loadbalancer.server.port=9999
      - traefik.docker.network=internal

