volumes:
  cs-logs:
    external: true
  crowdsec-db:
    external: true
  crowdsec-config:
    external: true
  cs-ing-db:
    external: true
  cs-ing-config:
    external: true
  cs-ing-logs:
    external: true

services:
  crowdsec:
    container_name: crowdsec
    image: "crowdsecurity/crowdsec:latest"
    networks:
      - crowdsec
      - monitoring
    environment:
      - "CUSTOM_HOSTNAME=cs-decision"
      - "GID=1000"
      - "LEVEL_INFO=true"
      - "TZ=${TZ}"
    ports:
      - "4242:4242/tcp"
      - "6060:6060/tcp"
      # - "8086:8080/tcp"
    restart: "always"
    volumes:
      - ${CONFIGDIR}/crowdsec/notifications:/etc/crowdsec/notifications
      - ${CONFIGDIR}/crowdsec/profiles.yaml:/etc/crowdsec/profiles.yaml
      - crowdsec-config:/etc/crowdsec
      - crowdsec-db:/var/lib/crowdsec/data
      - cs-logs:/var/log/crowdsec
    labels:
      - docker-volume-backup.stop-during-backup=true
  crowdsec-ingest:
    container_name: crowdsec-ingest
    image: "crowdsecurity/crowdsec:latest"
    networks:
      - crowdsec
      - monitoring
    environment:
      - "COLLECTIONS=crowdsecurity/linux crowdsecurity/traefik crowdsecurity/whitelist-good-actors"
      # known to have false positives and is CPU intensive
      - "DISABLE_SCENARIOS=crowdsecurity/http-bad-user-agent"
      # improves regex performance
      - "CROWDSEC_FEATURE_RE2_GROK_SUPPORT=true"
      - "CUSTOM_HOSTNAME=cs-ingest"
      - "GID=1000"
      # important to make this a worker
      - "DISABLE_LOCAL_API=true"
      - "LEVEL_INFO=true"
      - "LOCAL_API_URL=http://crowdsec:8080"
    ports:
      - "6061:6060/tcp"
    restart: "always"
    volumes:
      - cs-ing-config:/etc/crowdsec
      - cs-ing-db:/var/lib/crowdsec/data
      - cs-ing-logs:/var/log/crowdsec
    labels:
      - docker-volume-backup.stop-during-backup=true
