services:
  crowdsec:
    container_name: crowdsec
    image: "crowdsecurity/crowdsec:latest"
    networks:
      - crowdsec
      - default
    environment:
      - "CUSTOM_HOSTNAME=cs-decision"
      - "GID=1000"
      - "LEVEL_INFO=true"
      - "TZ=${TZ}"
    ports:
      - "4242:4242/tcp"
      - "6060:6060/tcp"
      # - "8086:8080/tcp"
    restart: "always"
    volumes:
      - "${CONFIGDIR}/crowdsec/config:/etc/crowdsec"
      - "${CONFIGDIR}/crowdsec/data:/var/lib/crowdsec/data"
      - "${CONFIGDIR}/crowdsec/logs:/var/log/crowdsec"
  crowdsec-ingest:
    container_name: crowdsec-ingest
    image: "crowdsecurity/crowdsec:latest"
    networks:
      - crowdsec
      - default
    environment:
      - "COLLECTIONS=crowdsecurity/linux crowdsecurity/traefik crowdsecurity/whitelist-good-actors"
      # known to have false positives and is CPU intensive
      - "DISABLE_SCENARIOS=crowdsecurity/http-bad-user-agent"
      # improves regex performance
      - "CROWDSEC_FEATURE_RE2_GROK_SUPPORT=true"
      - "CUSTOM_HOSTNAME=cs-ingest"
      - "GID=1000"
      # important to make this a worker
      - "DISABLE_LOCAL_API=true"
      - "LEVEL_INFO=true"
      - "LOCAL_API_URL=http://crowdsec:8080"
    ports:
      - "6061:6060/tcp"
    restart: "always"
    volumes:
      - "${CONFIGDIR}/crowdsec-ingest/config:/etc/crowdsec"
      - "${CONFIGDIR}/crowdsec-ingest/data:/var/lib/crowdsec/data"
      - "${CONFIGDIR}/crowdsec-ingest/logs:/var/log/crowdsec"
