services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    privileged: true
    restart: always
    environment:
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    network_mode: "host"
    ports:
      - "5380:5380/tcp"
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    volumes:
      - config:/etc/dns

volumes:
  config:
