services:
  dns1:
    container_name: dns1
    hostname: dns1.cwel.sh
    image: 'technitium/dns-server:latest'
    restart: always
    privileged: true
    network_mode: 'host'
    ports:
      - '5380:5380/tcp'
    environment:
      - DNS_SERVER_DOMAIN=dns1.cwel.sh
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    volumes:
      - ${DOCKERM}/dns:/etc/dns

  keepalived:
    image: shawly/keepalived:edge-7f210c3
    restart: always
    environment:
      TZ: ${TZ}
      KEEPALIVED_VIRTUAL_IP: 192.168.4.69
      KEEPALIVED_VIRTUAL_MASK: 24
      KEEPALIVED_CHECK_IP: 192.168.4.128
      KEEPALIVED_CHECK_PORT: 53
      KEEPALIVED_VRID: 150
      KEEPALIVED_INTERFACE: br0
      KEEPALIVED_PRIORITY: 255
      KEEPALIVED_STATE: MASTER
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
