name: matrix
services:
  cleanmedia:
    depends_on:
      - monolith
    environment:
      - CLEANMEDIA_OPTS=-c /etc/dendrite/dendrite.yaml -t 30 -l
      - CRON=0 0 * * *
    hostname: cleanmedia
    image: rogsme/cleanmedia
    networks:
      - proxy
    volumes:
      - ${DOCKERDIR}/matrix/config/dendrite:/etc/dendrite
      - ${DOCKERDIR}/matrix/config/media:/var/dendrite/media
      - /etc/localtime:/etc/localtime

  element-web:
    container_name: element-web
    depends_on:
      - monolith
    image: vectorim/element-web:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.element-web.entrypoints=websecure
      - traefik.http.routers.element-web.rule=Host(`im.cwel.sh`)
      - traefik.http.routers.element-web.tls.certresolver=le
      - traefik.http.services.element-web.loadbalancer.server.port=80
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DOCKERDIR}/matrix/element-web/config.json:/app/config.json

  matrix-postgres:
    container_name: matrix-postgres
    environment:
      - POSTGRES_DATABASE=dendrite
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=dendrite
    hostname: postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U dendrite
      timeout: 5s
      interval: 5s
      retries: 5
    image: postgres:15-alpine
    networks:
      - proxy
    restart: always
    volumes:
      - ${DOCKERDIR}/matrix/config/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime

  mautrix-discord:
    container_name: discord-bridge
    depends_on:
      - matrix-postgres
    hostname: discord
    healthcheck:
      test:
        - CMD-SHELL
        - test -f /data/config.yaml -a -f /data/registration.yaml
      timeout: 10s
      interval: 30s
      retries: 1
      start_period: 5s
    image: dock.mau.dev/mautrix/discord:latest
    networks:
      - proxy
    restart: "no"
    volumes:
      - ${DOCKERDIR}/matrix/config/discord:/data
      - /etc/localtime:/etc/localtime

  monolith:
    container_name: monolith
    depends_on:
      - matrix-postgres
    hostname: monolith
    image: ghcr.io/element-hq/dendrite-monolith:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.matrix-fed.entrypoints=matrix-federation
      - traefik.http.routers.matrix-fed.rule=Host(`m.cwel.sh`)
      - traefik.http.routers.matrix-fed.service=matrix
      - traefik.http.routers.matrix-fed.tls.certresolver=le
      - traefik.http.routers.matrix.entrypoints=matrix-client
      - traefik.http.routers.matrix.rule=Host(`m.cwel.sh`)
      - traefik.http.routers.matrix.tls.certresolver=le
      - traefik.http.services.matrix.loadbalancer.server.port=8008
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/matrix/config/dendrite:/etc/dendrite
      - /etc/localtime:/etc/localtime
      - ${DOCKERDIR}/matrix/config/media:/var/dendrite/media
      - ${DOCKERDIR}/matrix/config/jetstream:/var/dendrite/jetstream
      - ${DOCKERDIR}/matrix/config/search_index:/var/dendrite/searchindex
      - ${DOCKERDIR}/matrix/config/discord:/etc/discord
      - ${DOCKERDIR}/matrix/config/imsg:/etc/imsg

networks:
  proxy:
    name: proxy
    external: true