services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${DOCKERM}/backrest/data:/data
      - ${DOCKERM}/backrest/config:/config
      - ${DOCKERM}/backrest/cache:/cache
      - ${DOCKERM}/backrest/tmp:/tmp
      - ${DOCKERM}:/userdata
      - ${BRICK}:${BRICK} 
      - /home/cwel/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TZ}
    # ports:
    #   - "9898:9898"
    restart: unless-stopped
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.rule=Host(`backrest.${DOMAIN}`)
      - traefik.http.services.backrest.loadbalancer.server.port=9898
      - traefik.docker.network=internal