services:
  membarr:
      image: 'yoruio/membarr:latest'
      restart: unless-stopped
      container_name: membarr
      networks:
        - media
      volumes:
        - ${DOCKERM}/membarr:/app/app/config
      environment:
        - token=${MEMBARR_TOKEN}
