server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# local machine logs
scrape_configs:
  - job_name: auth
    static_configs:
    - targets:
        - localhost
      labels:
        job: authlogs
        __path__: /var/log/secure

  - job_name: traefik-internal
    static_configs:
    - targets:
        - localhost
      labels:
        job: traefiklogs
        instance: internal
        __path__: /var/log/internal/*.log

  - job_name: traefik-external
    static_configs:
    - targets:
        - localhost
      labels:
        job: traefiklogs
        instance: external
        __path__: /var/log/external/*.log

