services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # remote-api:
  #   image: kekru/docker-remote-api-tls:v0.5.0
  #   environment:
  #     - CREATE_CERTS_WITH_PW=${RAPIPASS}
  #     - CERT_HOSTNAME=${CERT_HOSTNAME}
  #   ports:
  #     - 2376:443
  #   volumes:
  #     - ${CONFIGDIR}/socket/certs:/data/certs
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

