services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    pid: "host"
    ports:
      - "6123:6123"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
      - "${CONFIGDIR}/glances/glances.conf:/glances/conf/glances.conf"
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - TZ=${TZ}
      - GLANCES_OPT=-C /glances/conf/glances.conf -w


