volumes:
  guacd:
    external: true
  guac-db:
    external: true

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    volumes:
      - guacd:/drive:rw
      - guacd:/record:rw
    # networks:
    #  - guac

  postgres:
    image: postgres:16-alpine
    container_name: guac-db
    restart: always
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data/guacamole
      - POSTGRES_DB=guac
      - POSTGRES_USER=guac
      - POSTGRES_PASSWORD=${GUAC_PG_PASS}
    volumes:
      # - ${CONFIGDIR}/guacamole/psql/init:/docker-entrypoint-initdb.d:z
      - guac-db:/var/lib/postgresql/data:Z
    # networks:
    #  - guac

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_DATABASE=guac
      - POSTGRESQL_USER=guac
      - POSTGRESQL_PASSWORD=${GUAC_PG_PASS}
    links:
      - guacd
    ports:
      - 8095:8080/tcp 
    expose:
      - 8080
    # networks:
    #  - internal
    #  - guac
    # labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=internal
    #  - traefik.http.routers.guacamole.rule=Host(`guac.${DOMAIN}`) && PathPrefix(`/guacamole`)
    #  - traefik.http.services.guacamole.loadbalancer.server.port=8080

