services:

  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    expose:
      - 80
    networks:
     - internal
    labels:
     - traefik.enable=true
     - traefik.http.routers.it-tools.rule=Host(`tools.${DOMAIN}`)
     - traefik.http.services.it-tools.loadbalancer.server.port=80
     - traefik.docker.network=internal

