services:
  traefik-kop-public:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=traefik-external-redis:6379"
      - "NAMESPACE=public"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=${HOSTNAME}-public"
      - "BIND_IP=${SERVER_IP}"
    depends_on:
      - socket-proxy
    networks:
      - kop
      - default
  traefik-kop-internal:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=traefik-internal-redis:6379"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=${HOSTNAME}-internal"
      - "BIND_IP=${SERVER_IP}"
    depends_on:
      - socket-proxy
    networks:
      - kop
      - default
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    networks:
      - default
    environment:
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
      - POST=0
      - SERVICES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    restart: always
    read_only: true
    tmpfs:
      - /run

