services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    networks:
      - internal
      - media
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/kavita:/config
      - ${RUST}/book:/data
    # ports:
    #   - 5000:5000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`kavita.${CASA}`)
      - traefik.http.services.kavita.loadbalancer.server.port=5000
      - traefik.docker.network=internal

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      - internal
      - media
    volumes:
      - ${RUST}/book:/books
      - ${RUST}/book/audio:/audiobooks
      - ${RUST}/audio:/podcasts
      - ${DOCKERM}/audiobookshelf:/config
      - ${DOCKERM}/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`abs.${CASA}`)
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
      - traefik.docker.network=internal

  # calibre-web:
  #   image: crocodilestick/calibre-web-automated:latest
  #   container_name: cweb
  #   environment:
  #     - PUID=1000
  #     - PGID=1001
  #     - TZ=${TZ}
  #     - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
  #   volumes:
  #     - ${DOCKERM}/cweb:/config
  #     - ${RUST}/book/inb:/cwa-book-ingest
  #     - ${RUST}/book:/calibre-library
  #     - ${DOCKERM}/cweb/plugs:/config/.config/calibre/plugins
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.cweb.rule=Host(`cweb.${CASA}`)
  #     - traefik.http.services.cweb.loadbalancer.server.port=8083
  #     - traefik.docker.network=internal

  # bookbounty:
  #   image: thewicklowwolf/bookbounty:latest
  #   container_name: bookbounty
  #   networks:
  #     - internal
  #     - media
  #   environment:
  #     - selected_path_type=folder
  #     - library_scan_on_completion=True
  #   volumes:
  #     - ${RUST}/book:/bookbounty/downloads
  #     - ${DOCKERM}/bookbounty:/bookbounty/config
  #     - /etc/localtime:/etc/localtime:ro
  #   # ports:
  #   #   - xxxx:5000
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.bookbounty.rule=Host(`bookbounty.${CASA}`)
  #     - traefik.http.services.bookbounty.loadbalancer.server.port=5000
  #     - traefik.docker.network=internal

  # ebookbuddy:
  #   image: thewicklowwolf/ebookbuddy:latest
  #   container_name: ebookbuddy
  #   networks:
  #     - internal
  #     - media
  #   environment:
  #     - auto_start=True
  #     - search_for_missing_book=True
  #   volumes:
  #     - ${DOCKERM}/ebookbuddy:/ebookbuddy/config
  #     - /etc/localtime:/etc/localtime:ro
  #   # ports:
  #   #   - xxxx:5000
  #   restart: unless-stopped
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.ebookbuddy.rule=Host(`ebookbuddy.${CASA}`)
  #     - traefik.http.services.ebookbuddy.loadbalancer.server.port=5000
  #     - traefik.docker.network=internal
