services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DOCKERM}/kavita:/config
      - ${RUST}/book:/data
    # ports:
    #   - 5000:5000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`kavita.${CASA}`)
      - traefik.http.services.kavita.loadbalancer.server.port=5000
      - traefik.docker.network=internal

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      - internal
    volumes:
      - ${RUST}/book:/books
      - ${RUST}/book/audio:/audiobooks
      - ${RUST}/audio:/podcasts
      - ${DOCKERM}/audiobookshelf:/config
      - ${DOCKERM}/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`abs.${CASA}`)
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
      - traefik.docker.network=internal

  calibre-web:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cweb
    networks:
      - internal
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
    volumes:
      - ${DOCKERM}/cweb:/config
      - ${RUST}/book/ing:/cwa-book-ingest
      - ${RUST}/book:/calibre-library
      - ${DOCKERM}/cweb/plugs:/config/.config/calibre/plugins
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.cweb.rule=Host(`cweb.${CASA}`)
      - traefik.http.services.cweb.loadbalancer.server.port=8083
      - traefik.docker.network=internal

  cweb-dl:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: cweb-dl
    networks:
      - internal
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: en
      USE_BOOK_TITLE: true
      TZ: ${TZ}
      APP_ENV: prod
      UID: 1000
      GID: 1000
      CWA_DB_PATH: /auth/app.db
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.cweb-dl.rule=Host(`cwebdl.${CASA}`)
      - traefik.http.services.cweb-dl.loadbalancer.server.port=8084
      - traefik.docker.network=internal
    volumes:
      - ${RUST}/book/ing:/cwa-book-ingest
      - ${DOCKERM}/cweb/app.db:/auth/app.db:ro

networks:
  internal:
    external: true
