services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    networks:
      - internal
    logging:
      options:
        max-size: 10m
    volumes:
      - ${DOCKERM}/freshrss/data:/var/www/FreshRSS/data
      - ${DOCKERM}/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: ${TZ}
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16 192.168.4.89
    labels:
     - traefik.enable=true
     - traefik.http.routers.freshrss.rule=Host(`frss.${DOMAIN}`)
     - traefik.http.services.freshrss.loadbalancer.server.port=8080
     - traefik.docker.network=internal
