services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAIN}
    volumes:
      - ${DOCKERM}/jellyfin:/config
      - ${RUST}:/data
      - ${DOCKERM}/sportyfin:/sports
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1901:1901/udp #optional
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8096/health']
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jelly.${DOMAIN}`)
      - traefik.docker.network=public
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - kop.namespace=public
    networks:
      - public
      - media
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  jellystat-db:
    image: 'postgres:15.2'
    shm_size: 1gb
    container_name: jellystat-db
    restart: unless-stopped
    networks:
      - media
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${JELLYPG_PASS}
    volumes:
      - ${DOCKERM}/jellystat/data:/var/lib/postgresql/data

  jellystat:
    image: 'cyfershepard/jellystat:latest'
    container_name: jellystat
    restart: unless-stopped
    networks:
      - internal
      - media
    environment:
      POSTGRES_USER: jellystat
      POSTGRES_PASSWORD: ${JELLYPG_PASS}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JELLYS_JWT}
      TZ: ${TZ}
    volumes:
      - ${DOCKERM}/jellystat/backup:/app/backend/backup-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellystat.rule=Host(`jellystat.${CASA}`)
      - traefik.docker.network=internal
      - traefik.http.services.jellystat.loadbalancer.server.port=3000
    depends_on:
      - jellystat-db
