services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ${BRICK}/wiki:/data
    command:
      - '*.zim'
    labels:
      - traefik.enable=true
      - traefik.http.routers.kiwi.rule=Host('wiki.${CASA}')
      - traefik.http.services.kiwi.loadbalancer.server.port=8080
      - traefik.docker.network=internal

networks:
  internal:
    external: true
