services:
  stash:
    image: ghcr.io/hotio/stash
    container_name: stash
    restart: unless-stopped
    # ports:
    #   - "9999:9999"
    # network_mode: host
    networks:
      - internal
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '2m'
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERM}/stash:/config
      - ${RUST}:/data
      - ${DOCKERM}/stash/metadata:/metadata
      - ${DOCKERM}/stash/cache:/cache
      - ${DOCKERM}/stash/blobs:/blobs
      - ${DOCKERM}/stash/generated:/generated
    labels:
      - traefik.enable=true
      - traefik.http.routers.stash.rule=Host(`stash.${CASA}`)
      - traefik.http.services.stash.loadbalancer.server.port=9999
      - traefik.docker.network=internal

networks:
  internal:
    external: true
