services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${DOCKERM}/backrest/data:/data
      - ${DOCKERM}/backrest/config:/config
      - ${DOCKERM}/backrest/cache:/cache
      - ${DOCKERM}/backrest/tmp:/tmp
      - /usr/bin/rclone:/usr/local/bin/rclone
      - /home/cwel/.config/rclone:/root/.config/rclone
      - ${FLASH}:${FLASH}
      - ${RUST}:${RUST}
      - ${BRICK}:${BRICK}
      - /opt:/userdata/opt
      - /home:/userdata/home
      - /etc:/userdata/etc
      - /var:/userdata/var
      - /usr:/userdata/usr
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TZ}
    # ports:
    #   - "9898:9898"
    restart: unless-stopped
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.rule=Host(`backrest.${DOMAIN}`)
      - traefik.http.services.backrest.loadbalancer.server.port=9898
      - traefik.docker.network=internal