# https://github.com/imputnet/cobalt/blob/main/docs/api-env-variables.md
services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt
    ports:
      - 127.0.0.1:1337:1337

    environment:
      API_URL: 'https://grab.cwel.sh'
      API_PORT: '1337'
      API_AUTH_REQUIRED: '1'
      API_KEY_URL: 'file:///keys.json'
      # COOKIE_PATH: '/cookies.json'
      YOUTUBE_SESSION_SERVER: 'http://yt-session-generator:8080'
    depends_on:
      yt-session-generator:
        condition: service_healthy

    networks:
      - public

    labels:
      - traefik.enable=true
      - traefik.http.routers.cobalt.rule=Host(`grab.${DOMAIN}`)
      - traefik.http.services.cobalt.loadbalancer.server.port=1337
      - traefik.docker.network=public
      - kop.namespace=public

    volumes:
      - ${DOCKERM}/cobalt/keys.json:/keys.json:ro
      # - ${DOCKERM}/cobalt/cookies.json:/cookies.json:ro

  yt-session-generator:
    image: linuxfight/yt-session-generator:main
    init: true
    restart: unless-stopped
    container_name: yt-session-generator
    ports:
      - 1335:8080
      - 5910:5910
    volumes:
      - ${DOCKERM}/cobalt/certs:/certs
    networks:
      - public
    environment:
      - SWAY_UNSUPPORTED_GPU=true
      - SWAY_RESOLUTION=1280x720
      - WAYVNC_PORT=5910
      - WAYVNC_ENABLE_AUTH=true
      - WAYVNC_USERNAME=wayvnc
      - WAYVNC_PASSWORD=wayvnc

networks:
  public:
    external: true
