services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11

    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt

    # ports:
    #   - 127.0.0.1:9000:9000

    # https://github.com/imputnet/cobalt/blob/main/docs/api-env-variables.md
    environment:
      API_URL: 'https://grab.cwel.casa'
      API_PORT: '1337'
      CORS_WILDCARD: '1'
      # COOKIE_PATH: '/cookies.json'

    networks:
      - internal

    labels:
      - traefik.enable=true
      - traefik.http.routers.cobalt.rule=Host(`grab.${CASA}`)
      - traefik.http.services.cobalt.loadbalancer.server.port=1337
      - traefik.docker.network=internal
      # Rewrite old /api/json endpoint to / for compatibility with old extensions
      - traefik.http.middlewares.cobalt-api-rewrite.replacepathregex.regex=^/api/json
      - traefik.http.middlewares.cobalt-api-rewrite.replacepathregex.replacement=/
      - traefik.http.routers.cobalt.middlewares=cobalt-api-rewrite

    # volumes:
    #   - ${DOCKERM}/cobalt/cookies.json:/cookies.json

  # yt-session-generator:
  #     image: ghcr.io/imputnet/yt-session-generator:webserver

  #     init: true
  #     restart: unless-stopped
  #     container_name: yt-session-generator
  #     labels:
  #       - com.centurylinklabs.watchtower.scope=cobalt

networks:
  internal:
    external: true
