services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11

    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt

    # ports:
    #   - 127.0.0.1:9000:9000

    # https://github.com/imputnet/cobalt/blob/main/docs/api-env-variables.md
    environment:
      API_URL: 'https://grab.cwel.sh'
      API_PORT: '1337'
      API_AUTH_REQUIRED: '1'
      API_KEY_URL: 'file:///keys.json'
      YOUTUBE_SESSION_SERVER: 'http://yt-session-generator:8080'
      # COOKIE_PATH: '/cookies.json'

    networks:
      - public

    labels:
      - traefik.enable=true
      - traefik.http.routers.cobalt.rule=Host(`grab.${DOMAIN}`)
      - traefik.http.services.cobalt.loadbalancer.server.port=1337
      - traefik.docker.network=public
      - kop.namespace=public

    volumes:
      - ${DOCKERM}/cobalt/keys.json:/keys.json:ro
      # - ${DOCKERM}/cobalt/cookies.json:/cookies.json:ro

  yt-session-generator:
    image: ghcr.io/imputnet/yt-session-generator:webserver

    init: true
    restart: unless-stopped
    container_name: yt-session-generator

    networks:
      - public

networks:
  public:
    external: true
