services:
  couchdb:
    container_name: obsi-db
    image: couchdb:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=${TZ}
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=${OBSI_LS_PW}
    networks:
      - internal
    volumes:
      - ${DOCKERM}/couchdb/data:/opt/couchdb/data
      - ${DOCKERM}/couchdb/local.ini:/opt/couchdb/etc/local.ini
    labels:
      - traefik.enable=true
      - traefik.http.routers.couchdb.rule=Host(`obdb.${CASA}`)
      - traefik.docker.network=internal
      - traefik.http.services.couchdb.loadbalancer.server.port=5984

networks:
  internal:
    external: true
