services:
  sftpgo:
    image: drakkan/sftpgo:v2-alpine
    networks:
      - internal
      - stack
    container_name: sftpgo
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 2022:2022 # SFTP
    expose:
      - 8080 # HTTP
      - 2022 # SFTP
      - 443 # HTTPS
      - 5007 # WEBDAV
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
      SFTPGO_DATA_PROVIDER__DRIVER: mysql
      SFTPGO_DATA_PROVIDER__NAME: sftpgo
      SFTPGO_DATA_PROVIDER__HOST: mysql
      SFTPGO_DATA_PROVIDER__PORT: 3306
      SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
      SFTPGO_DATA_PROVIDER__PASSWORD: ${SFTPGO_DB_PASS}
      SFTPGO_COMMON__DEFENDER__ENABLED: false
      SFTPGO_COMMON__DEFENDER__BAN_TIME: 15
      SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT: 100
      SFTPGO_COMMON__DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME: 15
    volumes:
      - ${DOCKERM}/sftpgo/data:/srv/sftpgo
      - ${RUST}:/srv/sftpgo/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sftpgo.rule=Host(`ftp.${CASA}`)"
      - traefik.docker.network=internal
      - traefik.http.services.sftpgo.loadbalancer.server.port=8080

  mysql:
    image: mysql:latest
    container_name: sftpgo-db
    networks:
      - stack
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: sftpgo
      MYSQL_USER: sftpgo
      MYSQL_PASSWORD: ${SFTPGO_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${SFTPGO_DB_PASS}
    volumes:
      - ${DOCKERM}/sftpgo/mysql:/var/lib/mysql

networks:
  internal:
    external: true
  stack:
    internal: true
