services:
  op-connect-api:
    network_mode: service:tscar-opc
    container_name: op-connect-api
    image: 1password/connect-api:latest
    expose:
      - 8080
    volumes:
      - ${DOCKERM}/op-sync/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - ${DOCKERM}/op-sync/data:/home/opuser/.op/data
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
    restart: unless-stopped

  op-connect-sync:
    network_mode: service:tscar-opc
    container_name: op-connect-sync
    image: 1password/connect-sync:latest
    volumes:
      - ${DOCKERM}/op-sync/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - ${DOCKERM}/op-sync/data:/home/opuser/.op/data
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
    restart: unless-stopped

  komodo-op:
    container_name: komodo-op
    image: ghcr.io/cwelsys/komodo-op:latest
    network_mode: service:tscar-opc
    depends_on:
      - op-connect-api
    environment:
      KOMODO_HOST: 'https://komo.cwel.sh'
      KOMODO_API_KEY: ${KOMO_API_KEY}
      KOMODO_API_SECRET: ${KOMO_API_SECRET}
      OP_CONNECT_HOST: 'http://op-connect-api:8080'
      OP_SERVICE_ACCOUNT_TOKEN: ${OP_ACCESS_TOKEN}
      OP_VAULT: '2ckfzps6ihnew6pf5rvbdysm2u'
      SYNC_INTERVAL: '1h'
      LOG_LEVEL: 'INFO'
    restart: unless-stopped

  tscar-opc:
    image: tailscale/tailscale:latest
    container_name: tscar-opc
    hostname: opc
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41244
      - TS_EXTRA_ARGS=--accept-dns=true
    volumes:
      - ${DOCKERM}/ts-opc:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:41244/healthz']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
