services:
  tscar-opc:
    image: tailscale/tailscale:latest
    container_name: tscar-opc
    hostname: opc
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41244
    ports:
      - 8420:8420
    volumes:
      - ${DOCKERM}/ts-opc:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://127.0.0.1:41244/healthz']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  op-connect-api:
    network_mode: service:tscar-opc
    container_name: op-connect-api
    image: 1password/connect-api:latest
    volumes:
      - ${DOCKERM}/op-sync/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - ${DOCKERM}/op-sync/data:/home/opuser/.op/data
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
      OP_HTTP_PORT: 8420
    restart: always
    depends_on:
      tscar-opc:
        condition: service_healthy

  op-connect-sync:
    network_mode: service:tscar-opc
    container_name: op-connect-sync
    image: 1password/connect-sync:latest
    volumes:
      - ${DOCKERM}/op-sync/1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - ${DOCKERM}/op-sync/data:/home/opuser/.op/data
    environment:
      OP_SESSION: /home/opuser/.op/1password-credentials.json
    restart: always
    depends_on:
      tscar-opc:
        condition: service_healthy

  komodo-op:
    container_name: komodo-op
    image: ghcr.io/cwelsys/komodo-op:latest
    network_mode: service:tscar-opc
    environment:
      KOMODO_HOST: 'https://komo.cwel.casa'
      KOMODO_API_KEY: ${KOMO_API_KEY}
      KOMODO_API_SECRET: ${KOMO_API_SECRET}
      OP_CONNECT_HOST: 'http://localhost:8420'
      OP_SERVICE_ACCOUNT_TOKEN: ${OP_ACCESS_TOKEN}
      OP_VAULT: ${OP_VAULT_UUID}
      SYNC_INTERVAL: '1h'
      LOG_LEVEL: 'INFO'
    restart: always
