services:
  rustdesk:
    container_name: rustdesk
    image: ghcr.io/rustdesk/rustdesk-server-s6:latest
    volumes:
      - ${DOCKERM}/rustdesk:/db
      - ${DOCKERM}/rustdesk:/data
    restart: unless-stopped
    environment:
      - RELAY=rdp.${CASA}:21117
      - ENCRYPTED_ONLY=1
      - DB_URL=/db/db_v2.sqlite3
      - KEY_PRIV=${RUSTDESK_PRIV}
      - KEY_PUB=${RUSTDESK_PUB}
      - RUST_LOG=debug
    ports:
      - 21116:21116/udp
    labels:
      - traefik.enable=true
