services:
  tailscale-wakeonlan:
    image: ghcr.io/andygrundman/tailscale-wakeonlan:latest
    hostname: wol
    container_name: ts-wol
    environment:
      - TAILSCALE_HOSTNAME=wol
      - TAILSCALE_AUTHKEY=${TS_AUTHKEY}
      # - WOL_NETWORK=192.168.1.0/24
    restart: unless-stopped
    volumes:
      - tailscale-wakeonlan-state:/var/lib/tailscale
networks:
  bridge:
    driver: bridge
volumes:
  tailscale-wakeonlan-state:
