services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - 9094:9090
    volumes:
      - ${DOCKERDIR}/prometheus:/etc/prometheus
      - prom_data:/prometheus
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.prometheus.rule=Host(`prometheus.cwel.sh`)'
    #   - traefik.http.routers.prometheus.tls=true
    #   - 'traefik.http.routers.prometheus.tls.certresolver=le'
    #   - 'traefik.http.services.gprometheus.loadbalancer.server.port=9090'
  grafana:
    image: grafana/grafana
    container_name: grafana
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANAPW}
    volumes:
      - ${DOCKERDIR}/grafana:/etc/grafana/provisioning/datasources
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`data.cwel.sh`)'
      - traefik.http.routers.grafana.tls=true
      - 'traefik.http.routers.grafana.tls.certresolver=le'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
      - 'homepage.group=System'
      - 'homepage.name=Grafana'
      - 'homepage.icon=grafana.png'
      - 'homepage.href=https://data.cwel.sh'
      - 'homepage.description=Data Visualization'

volumes:
  prom_data:
networks:
  proxy:
    external: true
