services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`logs.${INTDOMAIN}`)
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - traefik.docker.network=internal
