services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb2
    restart: unless-stopped
    networks:
      - traefik
    expose:
      - 8086
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=influx-org
      - DOCKER_INFLUXDB_INIT_BUCKET=influx-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - ${DOCKERM}/influxdb:/var/lib/influxdb2
      - ${DOCKERM}/influxdb-cfg:/etc/influxdb2

  loki:
    image: grafana/loki:2.9.11
    container_name: loki
    networks:
      - traefik
    user: 1000:1000
    command: -config.file=/etc/loki/config.yml
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ${DOCKERM}/loki:/etc/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - traefik
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    expose:
      - 9080
    depends_on:
      - loki
    volumes:
      - /var/log:/var/log
      - ${DOCKERM}/promtail:/etc/promtail

  grafana:
    image: grafana/grafana-oss:11.5.1
    container_name: grafana
    user: 1000:1000
    depends_on:
      - influxdb
      - loki
      - promtail
    restart: unless-stopped
    networks:
      - internal
      - traefik
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
    expose:
      - 3000
    volumes:
      - ${DOCKERM}/grafana:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=internal

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.115.0
    container_name: victoriametrics
    restart: unless-stopped
    networks:
      - traefik
      - crowdsec
      - internal
    expose:
      - 8428
    volumes:
      - ${DOCKERM}/vmetrics:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"

  db-backup:
    container_name: influxdb2-db-backup
    image: tiredofit/db-backup
    networks:
      - traefik
    volumes:
      - ${DOCKERM}/dumps/influxdb2:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=${TZ}
      - CONTAINER_NAME=influxdb2-db-backup
      - CONTAINER_ENABLE_MONITORING=FALSE
      # - DEBUG_MODE=TRUE
      - DEFAULT_INFLUX_VERSION=2
      - BACKUP_JOB_CONCURRENCY=1     # Only run one job at a time
      - DEFAULT_CHECKSUM=NONE        # Don't create checksums
      - DEFAULT_COMPRESSION=ZSTD     # Compress all with ZSTD
      - DEFAULT_BACKUP_INTERVAL=1440   # Backup every 1440 minutes
      - DEFAULT_BACKUP_BEGIN=2330      # Start backing up at 11:30
      - DEFAULT_CLEANUP_TIME=8640    # Cleanup backups after a week

      - DB01_TYPE=influx
      - DB01_HOST=influxdb
      - DB01_NAME=influx-bucket
      - DB01_USER=admin
      - DB01_PASS=${INFLUXDB_PASS}

