volumes:
  kasm:
    external: true

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    restart: unless-stopped
    networks:
      - internal
    environment:
      - KASM_PORT=8443
    ports:
      - 3069:3000
      - 8443:443
    volumes:
      - kasm:/opt
      - ${CONFIGDIR}/kasm:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.kasm.rule=Host(`kasm.${DOMAIN}`)
    #   - traefik.http.services.kasm.loadbalancer.server.port=3000
    #   - traefik.docker.network=internal

