volumes:
  mesh:
    external: true

services:
  meshcentral:
    container_name: mesh
    restart: unless-stopped
    image: ghcr.io/ylianst/meshcentral:master
    networks:
      - internal
    environment:
      - HOSTNAME=mesh.${DOMAIN}
      - REVERSE_PROXY=true
      - REVERSE_PROXY_TLS_PORT=7443
      - ALLOW_NEW_ACCOUNTS=true
    # ports:
    #   - 80:80
    #   - 443:443
    #   - 4433:4433
    volumes:
      - mesh:/opt/meshcentral
      - ${CONFIGDIR}/mesh:/opt/meshcentral/meshcentral-data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.mesh.rule=Host(`mesh.${DOMAIN}`)
      - traefik.http.services.mesh.loadbalancer.server.port=80
      - traefik.docker.network=internal
      # - traefik.http.routers.mesh.middlewares=auth-proxy@docker
