services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest-tracker
    networks:
      - internal
      - monitor
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${SPEED_API}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE= 7 */3 * * *
      - APP_TIMEZONE=${TZ}
      - APP_URL=https://speed.${INTDOMAIN}
      - ASSET_URL=https://speed.${INTDOMAIN}
    volumes:
      - ${DOCKERM}/speedtest:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.speed-test.rule=Host(`speed.${INTDOMAIN}`)
      - traefik.http.services.speed-test.loadbalancer.server.port=80
      - traefik.docker.network=internal
