services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/homeassistant/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    # devices:
    #   - /path/to/device:/path/to/device
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://127.0.0.1:8123' ]
      interval: 30s
      retries: 10
    labels:
      - homepage.group=Apps
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.png
      - homepage.href=https://home.${DOMAIN}
      - homepage.description=Open source home automation that puts local control and privacy first
      - homepage.weight=3
      - homepage.widget.type=homeassistant
      - homepage.widget.url=https://home.${DOMAIN}
      - homepage.widget.key=${ACCESS_TOKEN}
