services:
  portainer:
    container_name: portainer
    image: ngxson/portainer-ce-without-annoying:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - proxy
    labels:
      # Frontend
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.cwel.sh`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.tls.certresolver=le
      # Homepage
      - homepage.group=Management
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://portainer.cwel.sh
      - homepage.description=Docker container management
      - homepage.weight=1
      # - traefik.http.routers.edge.rule=Host(`edge.cwel.sh`)
      # - traefik.http.routers.edge.entrypoints=websecure
      # - traefik.http.services.edge.loadbalancer.server.port=8000
      # - traefik.http.routers.edge.service=edge
      # - traefik.http.routers.edge.tls.certresolver=le
networks:
  proxy:
    external: true
