services:
  osx:
    container_name: big-mac
    image: sickcodes/docker-osx
    dns:
      - 1.1.1.1
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - 5999:5999
      - 1234:1234
      - 50922:10022
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${DOCKERDIR}/osx/maindisk.qcow2:/image
      - ${DOCKERDIR}/osx/bootdisk.qcow2:/bootdisk
    environment:
      - SHORTNAME=ventura
      - IMAGE_PATH=/image
      - BOOTDISK=/bootdisk
      - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=bigmac
      - DISPLAY=:99
      - WIDTH=1920
      - HEIGHT=1080
      - NOPICKER=true
      - ADDITIONAL_PORTS=hostfwd=tcp::1234-:1234,
