services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich
    volumes:
      - ${FLASH}/image:/usr/src/app/upload
      - ${FLASH}/nextcloud/Photos:/mnt/photos
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - DB_USERNAME=immich
      - DB_PASSWORD=${IMMICH_PG_PASS}
      - REDIS_HOST=immich-redis
      - REDIS_HOSTNAME=immich-redis
      - DB_HOSTNAME=immich-db
    expose:
      - 2283
    depends_on:
      - immich-redis
      - immich-db
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - internal
      - stack
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`img.${CASA}`)
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.docker.network=internal

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-ml
    volumes:
      - ${FLASH}/image:/usr/src/app/upload
      - ${FLASH}/nextcloud/Photos:/mnt/photos
      - cache:/cache
    environment:
      - TZ=${TZ}
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=immich
      - DB_PASSWORD=${IMMICH_PG_PASS}
      - REDIS_HOST=immich-redis
      - REDIS_HOSTNAME=immich-redis
      - DB_HOSTNAME=immich-db
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - internal
      - stack

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    container_name: immich-redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - stack

  immich-db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-db
    environment:
      POSTGRES_PASSWORD: ${IMMICH_PG_PASS}
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DOCKERM}/immich:/var/lib/postgresql/data
    command: >-
      postgres -c shared_preload_libraries=vchord.so,vectors.so -c 'search_path="$$user", public, vectors, vchord' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: unless-stopped
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    shm_size: 128mb
    networks:
      - stack

networks:
  internal:
    external: true
  stack:
    internal: true

volumes:
  cache:
