services:
  db:
    image: mariadb:latest
    container_name: pterodactyl_mariadb
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${DOCKERM}/pterodactyl/panel/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: ${PT_SQL_PASS}
      MYSQL_ROOT_PASSWORD: ${PT_SQL_RPASS}
    networks:
      - pterodactyl

  cache:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped
    networks:
      - pterodactyl

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: unless-stopped
    stdin_open: true
    tty: true
    # port required if you do not use a reverse proxy
    #    ports:
    #      - 8080:80
    #      - 8443:443 # OPTIONAL
    volumes:
      - '${DOCKERM}/pterodactyl/panel/var/:/app/var/'
      - '${DOCKERM}/pterodactyl/panel/logs/:/app/storage/logs'
      - '${DOCKERM}/pterodactyl/panel/nginx/:/etc/nginx/conf.d/'
    environment:
      RECAPTCHA_ENABLED: false
      TZ: ${TZ}
      APP_TIMEZONE: ${TZ}
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: false
      APP_URL: https://gpanel.cwel.sh
      APP_SERVICE_AUTHOR: noreply@cwel.sh
      MAIL_FROM: noreply@cwel.sh
      MAIL_DRIVER: smtp
      MAIL_HOST: in-v3.mailjet.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${SMTP_USER}
      MAIL_PASSWORD: ${SMTP_PASS}
      MAIL_ENCRYPTION: false
      TRUSTED_PROXIES: '*'
      PTERODACTYL_TELEMETRY_ENABLED: false
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: pterodactyl
      DB_PASSWORD: ${PT_SQL_PASS}
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: cache
    networks:
      - internal
      - pterodactyl
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=internal'
      - 'traefik.http.routers.panel.rule=Host(`gpanel.${DOMAIN}`)'
      - 'traefik.http.services.panel.loadbalancer.server.port=80'

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: unless-stopped
    ports:
      - 2022:2022
    stdin_open: true
    tty: true
    environment:
      TZ: ${TZ}
      APP_TIMEZONE: ${TZ}
      WINGS_UID: 1000
      WINGS_GID: 1000
      WINGS_USERNAME: pterodactyl
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/containers/:/var/lib/docker/containers/'
      - '/etc/pterodactyl/:/etc/pterodactyl/'
      - '/var/lib/pterodactyl/:/var/lib/pterodactyl/'
      - '/var/log/pterodactyl/:/var/log/pterodactyl/'
      - '/tmp/pterodactyl/:/tmp/pterodactyl/'
      - ${DOCKERM}/traefik/letsencrypt:ro
    networks:
      - internal
      - wings0
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=internal'
      - 'traefik.http.routers.wings0.rule=Host(`wings0.${DOMAIN}`)'
      - 'traefik.http.services.wings0.loadbalancer.server.port=443'

networks:
  pterodactyl:
    name: pterodactyl
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: '172.50.0.0/16'
    driver_opts:
      com.docker.network.bridge.name: wings0
