services:
  rxdb:
    container_name: rx-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ${DOCKERM}/rxresume/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rxres
      POSTGRES_PASSWORD: ${RX_PG_PASS}
      POSTGRES_DB: rxres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data
    ports:
      - '9000:9000'
    networks:
      - internal
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_PW}
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.${CASA}`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.docker.network=internal

  chrome:
    image: ghcr.io/browserless/chromium:v2.18.0 # Upgrading to newer versions causes issues
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: ${CHROME_TOKEN}
      EXIT_ON_HEALTH_FAILURE: 'true'
      PRE_REQUEST_HEALTH_CHECK: 'true'

  rxresume:
    container_name: rxresume
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - rxdb
      - minio
      - chrome
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`resume.${CASA}`)
      - traefik.http.services.app.loadbalancer.server.port=3000
      - traefik.docker.network=internal
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: https://resume.${CASA}
      STORAGE_URL: https://minio.${CASA}

      # -- Printer (Chrome) --
      CHROME_TOKEN: ${CHROME_TOKEN}
      CHROME_URL: wss://crum.${CASA}

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://rxres:${RX_PG_PASS}@rxdb:5432/rxres

      # -- Auth --
      ACCESS_TOKEN_SECRET: ${RX_SECRET}
      REFRESH_TOKEN_SECRET: ${RX_REFRESH_SECRET}

      # -- Emails --
      MAIL_FROM: info@cwel.sh
      SMTP_URL: smtp://${SMTP_USER}:${SMTP_PASS}@${SMTP_HOST}:587

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      # STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: ${MINIO_PW}
      STORAGE_USE_SSL: 'false'
      STORAGE_SKIP_BUCKET_CHECK: 'false'

volumes:
  minio_data:
