services:
  rxdb:
    container_name: rx-db
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - stack
    volumes:
      - ${DOCKERM}/rxresume/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rxres
      POSTGRES_PASSWORD: ${RX_PG_PASS}
      POSTGRES_DB: rxres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rxres -d rxres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Storage (for image uploads)
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data
    networks:
      - internal
    volumes:
      - ${DOCKERM}/rxresume/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_PW}
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.${CASA}`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.docker.network=internal

  # Chrome Browser (for printing and previews)
  chrome:
    container_name: rxchrome
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    networks:
      - internal
    environment:
      HEALTH: 'true'
      TOKEN: ${CHROME_TOKEN}
      PROXY_HOST: 'crum.cwel.sh'
      PROXY_PORT: 443
      PROXY_SSL: 'true'
    labels:
      - traefik.enable=true
      - traefik.http.routers.crum.rule=Host(`crum.${CASA}`)
      - traefik.http.services.crum.loadbalancer.server.port=3000
      - traefik.docker.network=internal

  rxresume:
    container_name: rxresume
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    networks:
      - internal
      - stack
    depends_on:
      - rxdb
      - minio
      - chrome
    environment:
      # -- Environment Variables --
      PORT: 3000
      NODE_ENV: production

      # -- URLs --
      PUBLIC_URL: https://resume.cwel.sh
      STORAGE_URL: https://minio.cwel.sh

      # -- Printer (Chrome) --
      CHROME_TOKEN: ${CHROME_TOKEN}
      CHROME_URL: wss://crum.cwel.sh

      # -- Database (Postgres) --
      DATABASE_URL: postgresql://rxres:${RX_PG_PASS}@rxdb:5432/rxres

      # -- Auth --
      ACCESS_TOKEN_SECRET: ${RX_SECRET}
      REFRESH_TOKEN_SECRET: ${RX_REFRESH_SECRET}

      # -- Emails --
      MAIL_FROM: info@cwel.sh
      SMTP_URL: smtp://${SMTP_USER}:${SMTP_PASS}@${SMTP_HOST}:587

      # -- Storage (Minio) --
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      # STORAGE_REGION: us-east-1 # Optional
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: ${MINIO_PW}
      STORAGE_USE_SSL: 'false'
      STORAGE_SKIP_BUCKET_CHECK: 'false'

    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`resume.${CASA}`)
      - traefik.http.services.app.loadbalancer.server.port=3000
      - traefik.docker.network=internal

  db-backup:
    container_name: rxres-db-backup
    image: tiredofit/db-backup
    restart: unless-stopped
    networks:
      - stack
    volumes:
      - ${DOCKERM}/dumps/rxresume:/backup
    environment:
      - TIMEZONE=${TZ}
      - CONTAINER_NAME=rxres-db-backup
      - CONTAINER_ENABLE_MONITORING=FALSE
      # - DEBUG_MODE=TRUE

      - BACKUP_JOB_CONCURRENCY=1 # Only run one job at a time
      - DEFAULT_CHECKSUM=NONE # Don't create checksums
      - DEFAULT_COMPRESSION=ZSTD # Compress all with ZSTD
      - DEFAULT_BACKUP_INTERVAL=1440 # Backup every 1440 minutes
      - DEFAULT_BACKUP_BEGIN=2330 # Start backing up at 11:30
      - DEFAULT_CLEANUP_TIME=8640 # Cleanup backups after a week
      - DB01_TYPE=postgres
      - DB01_HOST=rxdb
      - DB01_NAME=rxres
      - DB01_USER=rxres
      - DB01_PASS=${RX_PG_PASS}
