services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_CONTEXT_LENGTH=32768
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_NO_CLOUD=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama.rule=Host(`slop.${CASA}`)
      - traefik.docker.network=internal
      - traefik.http.services.ollama.loadbalancer.server.port=11434
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama: {}
networks:
  internal:
    external: true
