volumes:
  membarr:
    external: true
services:
  membarr:
      image: 'yoruio/membarr:latest'
      restart: unless-stopped
      container_name: membarr
      networks:
        - media
      volumes:
        - membarr:/app/app/config
      environment:
        - token=${MEMBARR_TOKEN}
      labels:
        - docker-volume-backup.stop-during-backup=true
