volumes:
  muse:
    external: true

services:
  muse:
    container_name: muse
    image: ghcr.io/museofficial/muse:latest
    restart: always
    networks:
      - media
    volumes:
      - muse:/data
    environment:
      - DISCORD_TOKEN=${MUSE_TOKEN}
      - YOUTUBE_API_KEY=${GOOGLE_API}
      # - SPOTIFY_CLIENT_ID=
      # - SPOTIFY_CLIENT_SECRET=
    labels:
      - docker-volume-backup.stop-during-backup=true
