volumes:
  redbot:
    external: true

services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    networks:
      - media
    volumes:
      - redbot:/data
    environment:
      # - TOKEN=${REDBOT_TOKEN}
      # - PREFIX=.
      - TZ=${TZ}
      - PUID=1000
    labels:
      - docker-volume-backup.stop-during-backup=true
