volumes:
  homepage:
    external: true
  speed-db:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - internal
      - media
      - crowdsec
      - traefik
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=hp.${DOMAIN}
      - HOMEPAGE_VAR_DOMAIN_NAME=${DOMAIN}
      - HOMEPAGE_VAR_SERVER_IP=${SERVERIP}
      - HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN=${OPENWEATHERMAP_TOKEN}
      - HOMEPAGE_VAR_CROWDSEC_PASSWORD=${CROWDSEC_PASS}
      - HOMEPAGE_VAR_CROWDSEC_USERNAME=pbox
      - HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACC_ID}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_API_KEY=${CLOUDFLARE_API}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID=${TUNNEL_ID}
      - HOMEPAGE_VAR_TAILSCALE_API_KEY= ${TS_API}
      - HOMEPAGE_VAR_TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
    volumes:
      - ${CONFIGDIR}/homepage:/app/config
      - ${CONFIGDIR}/homepage/images:/app/public/images
      - /mnt/:/mnt:ro
      - homepage:/data
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`hp.${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=internal
      - docker-volume-backup.stop-during-backup=true

  hp-sockp:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: hp-sockp
    networks:
      - media
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1
      - TASKS=1
      - INFO=1
      - POST=0
      - NETWORKS=1
      - SERVICES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 2375:2375
    restart: always
    read_only: true
    tmpfs:
      - /run

  speedtest-tracker:
      image: lscr.io/linuxserver/speedtest-tracker:latest
      restart: unless-stopped
      container_name: speedtest-tracker
      networks:
        - internal
      environment:
          - PUID=1000
          - PGID=1000
          - APP_KEY=${SPEED_API}
          - DB_CONNECTION=sqlite
      volumes:
          - speed-db:/config
      labels:
          - traefik.enable=true
          - traefik.http.routers.speed-test.rule=Host(`speed.${DOMAIN}`)
          - traefik.http.services.speed-test.loadbalancer.server.port=80
          - traefik.docker.network=internal
