services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - internal
    environment:
      - HOMEPAGE_VAR_TITLE="Sup Ma'"
      - HOMEPAGE_VAR_SEARCH_PROVIDER=duckduckgo
      - HOMEPAGE_VAR_HEADER_STYLE=minimal
      - HOMEPAGE_VAR_WEATHER_CITY=${HOMEPAGE_VAR_WEATHER_CITY}
      - HOMEPAGE_VAR_WEATHER_LAT=${HOMEPAGE_VAR_WEATHER_LAT}
      - HOMEPAGE_VAR_WEATHER_LONG=${HOMEPAGE_VAR_WEATHER_LONG}
      - HOMEPAGE_VAR_WEATHER_TIME=${TZ}
      - HOMEPAGE_VAR_WEATHER_UNIT=imperial
      - HOMEPAGE_ALLOWED_HOSTS=hp.${DOMAIN}
      - OPEN_WEATHER_API=${OPEN_WEATHER_API}
    volumes:
      - ${CONFIGDIR}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage:/data
    restart: always
    command: [sh, -c, 'cp -n /app/config/tpl/*.yaml /app/config && node server.js']
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`hp.${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=internal
volumes:
  homepage:
