services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - internal
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=hp.${DOMAIN}
    volumes:
      - ${CONFIGDIR}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage:/data
    restart: always
    command: [sh, -c, 'cp -n /app/config/tpl/*.yaml /app/config && node server.js']
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`hp.${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=internal
volumes:
  homepage:
