services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - internal
      - crowdsec
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=hp.${DOMAIN}
      - HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN=${HOMEPAGE_VAR_OPENWEATHERMAP_TOKEN}
      - HOMEPAGE_VAR_CROWDSEC_PASSWORD=${CROWDSEC_PASS}
    volumes:
      - ${CONFIGDIR}/homepage:/app/config
      - ${CONFIGDIR}/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${RUST}:/mnt/media:ro
      - homepage:/data
    restart: always
    command: [sh, -c, 'cp -n /app/config/tpl/*.yaml /app/config && node server.js']
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`hp.${DOMAIN}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=internal
volumes:
  homepage:
