name: Sync Komodo Webhooks
on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: '0 0 * * *' # Optional: Daily sync

jobs:
  sync-webhooks:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Komodo Stack IDs
        id: get_stacks
        env:
          KOMODO_TOKEN: ${{ secrets.KOMODO_TOKEN }}
        run: |
          STACK_IDS=$(curl -s -H "Authorization: Bearer $KOMODO_TOKEN" \
            "$KOMODO_API_URL/stacks" | jq -r '.[].id')
          echo "STACK_IDS=$(echo $STACK_IDS | tr ' ' ',')" >> $GITHUB_OUTPUT

      - name: Create/Update GitHub Webhooks
        run: |
          for STACK_ID in ${STACK_IDS//,/ }; do
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/hooks" \
              -d '{
                "name": "web",
                "active": true,
                "events": ["push"],
                "config": {
                  "url": "https://komo.cwel.sh/listener/github/stack/$STACK_ID/deploy",
                  "content_type": "json",
                  "secret": "${{ secrets.KOMODO_WEBHOOK_SECRET }}"
                }
              }'
          done
        env:
          STACK_IDS: ${{ steps.get_stacks.outputs.STACK_IDS }}
